### ISSUE TITLE
Field offsets in 64-bit binaries

### ISSUE THREAD

**Issue by zeobviouslyfakeacc** [djkaty/Il2CppInspector#10]
Hi! So the field offsets always looked a bit weird for me in The Long Dark, e.g.:

```csharp
public class GlobalSaveGameFormat // TypeDefIndex: 9029
{
	// Fields
	public int m_Version; // 0x10
	public string m_GameManagerSerialized; // 0x20
	public string m_HudManagerSerialized; // 0x30
[...]
	public string m_InfectionSerialized; // 0x240
	public string m_InfectionRiskSerialized; // 0x250
	public string m_LogSerialized; // 0x18
	public string m_RestSerialized; // 0x10
	public string m_FlyOverSerialized; // 0x10
```

where pointers were aligned to 16 bytes instead of just the usual 8, and after some number of fields, the offsets started going back down to previously-used offsets.

I think the issue is that even in this 64-bit binary, the type of Il2CppMetadataRegistration::fieldOffsets is still int32_t**. However, in Il2CppInspector.cs, the offsets are read using `BinaryImage.ReadWord()`:
```csharp
for (var f = 0; f < def.field_count; f++)
    offsets.Add(def.fieldStart + f, available? BinaryImage.ReadWord() : 0);
```
Considering that the type is int32_t**, this method should probably use BinaryImage.ReadInt32(), but because that method doesn't exist yet and I'm lazy, I just used BinaryImage.ReadUInt32() for a small-scale test, and now the field offsets look correct:
```csharp
public class GlobalSaveGameFormat // TypeDefIndex: 9029
{
	// Fields
	public int m_Version; // 0x10
	public string m_GameManagerSerialized; // 0x18
	public string m_HudManagerSerialized; // 0x20
[...]
	public string m_InfectionSerialized; // 0x128
	public string m_InfectionRiskSerialized; // 0x130
	public string m_LogSerialized; // 0x138
	public string m_RestSerialized; // 0x140
	public string m_FlyOverSerialized; // 0x148
[...]
	public string m_NPCGlobalSerialized; // 0x250
	public string m_PackManagerGlobalSerialized; // 0x258 <-- the last field of the class
```

I only have TLD's 64-bit binary to work with, so I don't know whether int32_t** is the correct type for all 64-bit binaries, but if it is, that `ReadWord` should probably be changed to a `ReadInt32` 😄

**Comment by djkaty** [comment]
Excellent, thank you. I'm winding down for Christmas now but I have a fairly substantial testbed of binaries that people have sent me over the years including a number of 64-bit ones so I will make this change, run it through the test suite and see how the field offsets come out then we can go from there. It will be after Christmas though.

Thanks for the feedback! I'll respond again when there is some change.

**Comment by djkaty** [comment]
Oh, could you attach the binary and metadata files you're working with please? That would be great!

**Comment by djkaty** [comment]
I've now looked over Pokemon Go, Hearthstone and as it turned out I owned the IL2CPP build of The Long Dark on Steam, plus some test assemblies, and I think you're absolutely right, for some binaries it makes no difference but for others using ReadUint32() gives more sane results, so I've fixed this in https://github.com/djkaty/Il2CppInspector/commit/0b868aae36a619dedc2a8ba770a6c17561d413d1

Thanks for the report!

**Comment by zeobviouslyfakeacc** [comment]
Awesome, thank you! 😄 

Also, I just noticed I completely forgot to upload the binary and metadata file! Sorry about that! I also took a break over Christmas, and I guess that fell between the cracks 😅
