### ISSUE TITLE
Expose MemoryInformation.h definitions

### ISSUE THREAD

**Issue by vfsfitvnm** [djkaty/Il2CppInspector#100]
Hey Katy!
I see you recently added a lot more definitions - and that's fantastic, thanks!

It would be cool if you could also add definitions from `MemoryInformation.h` ([example](https://gitlab.eecs.umich.edu/jsschaf/updated-gameday-mr/-/blob/67bceead846857ade90d1362b0a3dd46f2d23a7e/app/Il2CppOutputProject/IL2CPP/libil2cpp/vm/MemoryInformation.h)).

In fact, the api `il2cpp_capture_memory_snapshot` gives access to `Il2CppManagedMemorySnapshot`, which contains succulent data which may be useful at runtime.

Please let me know in case you were already aware of these definition, but you somehow found out they weren't necessary, thanks!

**Comment by djkaty** [comment]
Checked it out, should be doable. I will add it soon-ish 👍

**Comment by djkaty** [comment]
Added in commit https://github.com/djkaty/Il2CppInspector/issues/100 - hope that helps! Let me know / re-open the issue if there are any problems!
