### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by NotWaterScriptNhttp** [djkaty/Il2CppInspector#101]
Hello am trying to disassemble the il2cpp file but IL2CPPInspector shows me this message. It works with IL2CPP dumper but not with the IL2CPPInspector.
[GameAssembly.zip](https://github.com/djkaty/Il2CppInspector/files/5523095/GameAssembly.zip)

thx pls fix

**Comment by NotWaterScriptNhttp** [comment]
This Thread refers to [Sequence contains no matching element #95 ](https://github.com/djkaty/Il2CppInspector/issues/95)

**Comment by djkaty** [comment]
This issue is now resolved in the latest commit - enjoy! Let me know if you have any problems with it.
