### ISSUE TITLE
C Parser: Encountered errors during parse

### ISSUE THREAD

**Issue by MerzZly** [djkaty/Il2CppInspector#102]
Hello, I try add metadata to ghidra, but get C Parser error.

![Screen](https://user-images.githubusercontent.com/74457253/99147805-da097400-2694-11eb-85ec-01516a41cabd.png)

- OS: Windows 10 x64
- Il2CppInspector: 2020.2
- Ghidra: 9.1.2
- Unity version: 2017.4.30.0

Files (48 mb): https://mega.nz/file/pDRmzDpL#ay8EMQi4Jzw3ud7eOizijtEly5eY1RgszyUfyU14yqM

**Comment by djkaty** [comment]
Hey, the file is no longer available, could you re-upload it for me? 🙂

**Comment by MerzZly** [comment]
@djkaty https://mega.nz/file/FPACnBiT#ay8EMQi4Jzw3ud7eOizijtEly5eY1RgszyUfyU14yqM

**Comment by djkaty** [comment]
Got it, thank you! I will look into this shortly :)

**Comment by djkaty** [comment]
For some reason Ghidra considers "_extension" to be a reserved keyword. This issue is fixed in https://github.com/djkaty/Il2CppInspector/commit/d67ef3e5ed9456334bec9253a9b29436d728d835 - thank you for the report! Feel free to re-open the issue if you still have problems.
