### ISSUE TITLE
Is there a way I could turn an IL2Cpp dll into a C# dll?

### ISSUE THREAD

**Issue by l-7777777** [djkaty/Il2CppInspector#103]
I am attempting to reverse engineer a Unity game, but it is obfuscated with BeeByte. I tried Beeless, but the game uses Il2Cpp instead of C# dlls. Is there any way I can turn this dll into a C# dll with this?

**Comment by djkaty** [comment]
No, that would require turning the compiled C++ code back into IL, there is no trivial way to do that unfortunately!
