### ISSUE TITLE
Detecting when is possible to call il2cpp init?

### ISSUE THREAD

**Issue by AriciducaZagaria** [djkaty/Il2CppInspector#104]
I'm working on a dll that needs to be injected at the start of the game.
On injection the cpp project sends me access violation errors.

I solved this by sleeping the thread created at dll attach and then call the il2cppinit function. But this is not a good fix.

Is there any way to detect if il2cpp has loaded and then call il2cpp init?

**Comment by djkaty** [comment]
Did you find a solution to this?

**Comment by pierluigizagaria** [comment]
I was attaching the dll to the wrong dll and felt dumb about the question. 
However, i did not detected it by a function call, but just by loading the files on a correct way. Is there any other way to do this?

Sorry for my inexperience.

**Comment by djkaty** [comment]
There probably is but I'd have to look at the code and figure it out. I usually just attach the DLL after the target app has finished loading. You can fudge it and add in a delay/sleep at the start of your injected code if you need to. IL2CPP should initialize as soon as the app loads though.
