### ISSUE TITLE
Generated il2cpp.py: getAllScripts() no longer a function

### ISSUE THREAD

**Issue by djm1176** [djkaty/Il2CppInspector#105]
I am trying to run the generated il2cpp.py script within the newest version of Ghidra 9.2, however the generated script returns the following error:

`Traceback (most recent call last):
  File "...\il2cppInspector\il2cpp.py", line 178, in <module>
    CustomInitializer()
  File "...\il2cppInspector\il2cpp.py", line 64, in GetScriptDirectory
    return next(iter(filter(lambda x: x.getName() == 'il2cpp.py', GhidraScriptUtil.getAllScripts())), None).getParentFile().toString()
AttributeError: type object 'ghidra.app.script.GhidraScriptUtil' has no attribute 'getAllScripts'`

I am led to believe that the `getAllScripts` function is deprecated

**Comment by djkaty** [comment]
Duplicate of https://github.com/djkaty/Il2CppInspector/pull/86

This issue is resolved in the master branch already :)

**Comment by djm1176** [comment]
Oh shoot, thank you djkaty.
