### ISSUE TITLE
Error: The supplied metadata file is not valid

### ISSUE THREAD

**Issue by zexorex** [djkaty/Il2CppInspector#109]
I am trying to put the global-metadata.dat file from the game genshin impact but the error stated on the title pops up everytime. Whats the reason and how do i fix this ?

**Comment by ngoalong123** [comment]
> I am trying to put the global-metadata.dat file from the game genshin impact but the error stated on the title pops up everytime. Whats the reason and how do i fix this ?

that game encrypted global-metadata.dat file.

**Comment by djkaty** [comment]
Yep that's correct, the games by MoHiYo encrypt global-metadata.dat. I'm aware of the issue and it is on my list of things to look at, but I have no timeline on that I'm afraid.

**Comment by djkaty** [comment]
Some miHoYo games are now processed by the latest build of Il2CppInspector. You need to download the miHoYo plugin with the get-plugins.ps1/get-plugins.sh script or manually from the plugins repo, enable it and select the correct game. More details in the README on the front page of this repo.
