### ISSUE TITLE
Problem of IL 24.4

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#110]
When using latest code.

`Il2CppInspector Command-Line Edition
Version 2020.2.1
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.4
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Unknown symbol type: 2c   0000000005614542   radr://5614542
Symbol table(s) found with 14414 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x00000000000D3B8C
CodeRegistration struct found at 0x0000000002F84530 (file offset 0x02F84530)
MetadataRegistration struct found at 0x0000000003017368 (file offset 0x03017368)
IL2CPP binary version 24.4
Index was outside the bounds of the array.
Analyze IL2CPP data: 26.13 sec`

When use 2020.2.1
`Il2CppInspector Command-Line Edition
Version 2020.2.1
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.4
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Unknown symbol type: 2c   0000000005614542   radr://5614542
Symbol table(s) found with 14414 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x00000000000D3B8C
CodeRegistration struct found at 0x0000000002F84530 (file offset 0x02F84530)
MetadataRegistration struct found at 0x0000000003017368 (file offset 0x03017368)
IL2CPP binary version 24.4
Index was outside the bounds of the array.
Analyze IL2CPP data: 2.79 sec`

Here is the binaries. Thanks.
[download](https://www.dropbox.com/s/9a4wo55v8vem5r3/data.zip?dl=0)

BR,

**Comment by djkaty** [comment]
This should be fixed in the latest commit! Thanks once again for the bug report <3

**Comment by cctgapp** [comment]
> This should be fixed in the latest commit! Thanks once again for the bug report <3

Confirmed fixed. Thanks!!
