### ISSUE TITLE
index was outside the bounds of the array

### ISSUE THREAD

**Issue by busmanl30** [djkaty/Il2CppInspector#111]
I tried dumping a free game from steam, "Pixel strike 3d" and was unable to use the il2cppinspector and it gave me "index was outside the bounds of the array il2cpp". The dump works fine on il2cppdumper but im unable to dump it using inspector so i can make a project using the sdk

**Comment by djkaty** [comment]
Have you tried the latest commit?

**Comment by busmanl30** [comment]
I guess i havent, im new to github so i dont really understand how to use it where can io try the latest commit

**Comment by busmanl30** [comment]
Disregard, built it just now works fine appreciate your time and effort for this wonderful tool 👍

**Comment by djkaty** [comment]
Hey no problem, in the case of my specific project you can follow the instructions at https://github.com/djkaty/Il2CppInspector#build-instructions as you probably already found, but the overall steps are the same for most projects on github. You run `git clone <url>` , then `cd <project-dir>` and then the instruction to start the build depends on the particular GitHub project. Anyway glad you got it working and that it is useful to you! ❤
