### ISSUE TITLE
Deobfuscate

### ISSUE THREAD

**Issue by dfdfdfs** [djkaty/Il2CppInspector#114]
Hello, can you add an deobfuscator like this project?

https://github.com/OsOmE1/AUDeobfuscator

AUDeobfuscator not work

**Comment by djkaty** [comment]
As a rule the only de-obfuscation I will add to Il2CppInspector is that which is used by a significant body of IL2CPP applications; de-obfuscation on a per application basis is outside the scope of the project.

Having said that, generic comparative de-obfuscation of IL symbols between two applications of the type performed by @OsOmE1's tool was added to the roadmap a few days ago. There is no ETA date for this yet beyond "sometime next year".

All of that notwithstanding, I do recognize the need for additional processing in some cases, and there has been a rise in forks lately with hardcoded modifications to just deal with one binary. To this end, the next release of Il2CppInspector - coming in the next weeks - will introduce a plugin system that will allow people to create their own mods for Il2CppInspector to deal with cases like this. I had been planning to contact the author of AUDeobfuscator about converting his work to a plugin once the plugin SDK is ready.

**Comment by OsOmE1** [comment]
@djkaty feel free to add me on discord because I have archived AUDeobfuscator but I have not stopped working on deobfuscation. I think I have some useful insights if you want to discuss on discord. @OsOmE1#0019

**Comment by djkaty** [comment]
@OsOmE1 done!

**Comment by OsOmE1** [comment]
@djkaty my discord account got banned for retarded reasons can you please add me on OsOmE1#9672
