### ISSUE TITLE
Suggestion C++ Enum Class

### ISSUE THREAD

**Issue by std-nullptr** [djkaty/Il2CppInspector#115]
Would it be possible to adjust the enums for the C++ portion of il2cpp-types.h so that they are enum classes? It would help clean things up in my opinion and since they are scoped you wouldn't have to worry about name conflicts.

```c++
enum class Name__Enum : int32_t {
    Field1 = 0x00000000,
    Field2 = 0x00000001,
    Field3 = 0x00000002,
    Field4 = 0x00000003
}

auto test = app:Name__Enum::Field1;
```

**Comment by djkaty** [comment]
This enhancement is implemented in commit https://github.com/djkaty/Il2CppInspector/commit/956cea05539b33bc3aaddaca2f5cf41177d16add. Thanks for the suggestion!
