### ISSUE TITLE
re-ordering the fields

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#117]
Using latest codes.

`Il2CppInspector Command-Line Edition
Version 2020.2.1
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.2
Unknown symbol type: 2c   0000000005614542   radr://5614542
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000100000000
Symbol table(s) found with 64 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000100279130
CodeRegistration struct found at 0x00000001050AED10 (file offset 0x050AED10)
MetadataRegistration struct found at 0x0000000105267EF8 (file offset 0x05267EF8)
The detected Il2CppCodeRegistration / Il2CppMetadataRegistration structs do not pass validation. This may mean that their fields have been re-ordered as a form of obfuscation and Il2CppInspector has not been able to restore the original order automatically. Consider re-ordering the fields in Il2CppBinaryClasses.cs and try again.
Analyze IL2CPP data: 22.44 sec`

[download](https://www.dropbox.com/s/o2084t19rp1ultr/data.zip?dl=0)

**Comment by djkaty** [comment]
Fixed in the latest commit. Merry Xmas :)

**Comment by cctgapp** [comment]
> Fixed in the latest commit. Merry Xmas :)

Great.
Merry Xmas to you too.
