### ISSUE TITLE
Where i can get UnityPlayer.dll for miHoYo Plugin?

### ISSUE THREAD

**Issue by ngoalong123** [djkaty/Il2CppInspector#118]
Hello Madam!. Can i ask you a question? Where i can get UnityPlayer.dll for miHoYo Plugin?

**Comment by djkaty** [comment]
From the root folder of the PC version of the game you want to dump.

**Comment by ngoalong123** [comment]
Did it support dump mobile version?

Vào 22:56, Th 3, 29 thg 12, 2020 Katy <notifications@github.com> đã viết:

**Comment by djkaty** [comment]
The drop-down box to select a game in the miHoYo plugin settings dialog box shows which platforms are supported for which game.

**Comment by ngoalong123** [comment]
But if don't select UnityPlayer.dll i can not save setting. You can try

Vào 23:02, Th 3, 29 thg 12, 2020 Katy <notifications@github.com> đã viết:

**Comment by djkaty** [comment]
You need UnityPlayer.dll from the PC version of the game regardless of whether you are dumping the PC or mobile versions.

**Comment by ngoalong123** [comment]
Ahh ok tks u

Vào 23:06, Th 3, 29 thg 12, 2020 Katy <notifications@github.com> đã viết:
