### ISSUE TITLE
Can't dump .bin with *-maps.txt

### ISSUE THREAD

**Issue by AndnixSH** [djkaty/Il2CppInspector#119]
It does nothing when you drag *-maps.txt and .bin file, until you dropped metadata.dat file that it will do anything
Dropping or selecting maps.txt will show an error "Sequence contains no elements"

![image](https://user-images.githubusercontent.com/40742924/103311475-bdde4e00-4a1a-11eb-9851-9976487f01a5.png)

https://sbupload.com/51a57c57360d0c9a

**Comment by djkaty** [comment]
This should be fixed in the latest commits, let me know how you get on :)
