### ISSUE TITLE
Ghidra rebases dumped ELF files

### ISSUE THREAD

**Issue by MerzZly** [djkaty/Il2CppInspector#120]
Hello, how can I supply a dump of libil2cpp.so?

I use [memdumper](https://github.com/kp7742/MemDumper) to dump libil2cpp.so. 
And when I supply it to Il2CppDumper it works, but it doesn't for Il2CppInspector. I tried with and without 'raw' option.

Error message for raw: "Object reference not set to an instance of an object".
Error message for rebuilt: "Sequence contains no matching element".

Command-line `--image-base` doesn't work for this version.

Is the GameGurdian only one option?

- Il2CppDumper: 2020.2.1

**Comment by djkaty** [comment]
Are you using the latest commit?

**Comment by MerzZly** [comment]
I'm using build from "Latest release", but I've just noticed that there was "preview" in readme.

**Comment by djkaty** [comment]
You need to build the latest commit. Rebasing was added since the last release; it's in 2021.1 Preview 🙂

**Comment by MerzZly** [comment]
It works, thanks)
I hope that the function will be added in Gui, I mean image base.

**Comment by djkaty** [comment]
The rebase option is available in the 'Import options' button at the bottom right of the GUI before you load a file 🙂

Thanks for the reporting on the Ghidra bug and the fix, I will get that fixed over the next days!

**Comment by djkaty** [comment]
The rebasing issue in Ghidra _should_ be fixed now. Please try it and let me know how you get on :-)

**Comment by MerzZly** [comment]
I checked it with Gui and it works fine.

**Comment by djkaty** [comment]
Excellent! Thank you for the report. Closing issue.
