### ISSUE TITLE
I try to use this to unlock ll2cpp.so file in wild rift but its failed

### ISSUE THREAD

**Issue by deadnote154** [djkaty/Il2CppInspector#122]
I try to use this to unlock ll2cpp.so file in wild rift but its failed

its giving me error 
"The detected ll2CppCodeRegistration / ll2CppMetadataRegistration structs do not pass validation.
this may mean that their fields have been re-ordered as a form of obfuscation - this scenario is not currently supported by ll2CppInspector. consider re-ordering the fields in ll2CppBinaryClasses.cs and try again.

**Comment by djkaty** [comment]
Are you using the latest commit?

**Comment by deadnote154** [comment]
This version Il2CppInspector 2020.2.1 of .exe file i downloaded latest release @djkaty

**Comment by djkaty** [comment]
That's not the latest commit. Clone the repo and try the latest commit.

**Comment by deadnote154** [comment]
its okay to use the visual studio community to compile this to exe file?

**Comment by djkaty** [comment]
Yes :-) Once you have installed it, follow the instructions here:

https://github.com/djkaty/Il2CppInspector#build-instructions

**Comment by deadnote154** [comment]
dude help after i done that how can i convert it to .exe sorry beginner for C# visual studio. @djkaty im done to the 
dotnet publish -c Release   but when i try to use the plugines it give me error "cannot be loaded because runnning scripts is disabled on this system
When i try to use Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/[win|osx|linux]-x64/publish/Il2CppInspector.exe. its not detecting the libil2cpp.so and global metadata.dat. i put it on same folder of the exe file  Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/[win|osx|linux]-x64/publish/  Il2CppInspector.exe. Please help

**Comment by deadnote154** [comment]
I fix it already thank you so much @djkaty I will donate if i make it

**Comment by djkaty** [comment]
Glad to hear you got it compiled :) So you were able to get Wild Rift to open?

**Comment by deadnote154** [comment]
yeah, but now i find it hard cause im benigger to unlock the skins for wild rift. I will come again if i can unlock one skins of it. Did you try to unlock one @djkaty

**Comment by djkaty** [comment]
I don't play the games, I'm just the tool maintainer. I'll close the issue since Il2CppInpsector is now working for you. Good luck!
