### ISSUE TITLE
Function start address often off by 1

### ISSUE THREAD

**Issue by rustyx** [djkaty/Il2CppInspector#123]
Have a look at the example C# output below

		public override void GenerateIV(); // 0x02E3CFE0-0x02E3D014
		public override void GenerateKey(); // 0x02E3D014-0x02E3D047
		public override ICryptoTransform CreateDecryptor(byte[] rgbKey, byte[] rgbIV); // 0x02E3D046-0x02E3D0C1
		public override ICryptoTransform CreateEncryptor(byte[] rgbKey, byte[] rgbIV); // 0x02E3DC68-0x02E3DCE3
		public override ICryptoTransform CreateDecryptor(); // 0x02E3DE12-0x02E3DE67
		public override ICryptoTransform CreateEncryptor(); // 0x02E3DE66-0x02E3DEBC
		protected override void Dispose(bool disposing); // 0x02E3DEBC-0x02E3DEF3

Notice how `GenerateKey()` ends at `..047` and the next function, `CreateDecryptor()`, starts at `..046`.
So 1 byte too early.
This seems to happen quite a lot... any idea what could be the issue?
Sorry the project is a bit huge to attach (2 GB). But I'm happy to provide more details if needed.

![func-too-early](https://user-images.githubusercontent.com/1296899/104137676-dd706180-539e-11eb-817c-433d61b0c4b4.png)

**Comment by djkaty** [comment]
That's really weird, I use the IDA scripts all the time and haven't had that problem. What file format is it, has it been rebased/unpacked/otherwise modified by a 3rd party tool, and what commit of Il2CppInspector are you using?

If you can attach just the global-metadata.dat and GameAssembly.dll (or other binary), I can re-create the script and look into this.

**Comment by rustyx** [comment]
Here's the [zip](http://rustyx.org/temp/x86.zip) with libil2cpp.so, a 32-bit linux ELF.
The original C# code seems to have been obfuscated by beebytes. But I don't see how that can cause the function addresses to shift.

**Comment by djkaty** [comment]
This issue should now be fixed in the latest commit. Please give it a go and let me know how you get on :-)

**Comment by rustyx** [comment]
Looks good now. Thanks!
