### ISSUE TITLE
Suggestion: Allow reading the contents of arrays loaded from metadata

### ISSUE THREAD

**Issue by tech-ticks** [djkaty/Il2CppInspector#124]
I've been trying to read the contents of a static array, but I could only find calls to `RuntimeHelpers.InitializeArray()` and pointers that are loaded at runtime in the code. Since it seems like static (and maybe also non-static constant arrays?) are loaded from `global-metadata.dat`, it would be great if there was a way to access the data these arrays and/or the offset of the data inside `global-metadata.dat` with Il2CppInspector.

**Comment by djkaty** [comment]
Static array metadata offsets plus an 8-byte preview of the data are already output in the C# and DLL as comments and MetadataPreview attributes respectively. Note that .NET compiles static array initializers as PrivateImplementationDetails classes and the only way to discern which class maps to which array is by disassembling the array member owner class's static constructor. This issue has a more in-depth explanation with code: https://github.com/djkaty/Il2CppInspector/issues/59

Hopefully I haven't misunderstood what you're asking for!

**Comment by tech-ticks** [comment]
I see, thank you very much for your quick reply and explanation!

**Comment by djkaty** [comment]
You're welcome :)
