### ISSUE TITLE
Switch to specify the file output type for CLI

### ISSUE THREAD

**Issue by RaenonX** [djkaty/Il2CppInspector#128]
Currently, it seems that all types of output like `py`, `cs`, `cpp`, `json`, `dll` cannot be disabled.

However, sometimes I would like to only grab the `cs` output and not the others.

> Or maybe this is already available but missing somewhere in the doc?

My suggestions are:
- Have a switch like `--no-py` for disabling python output.
  - The cons of this is that if I **only** want the `cs` output, I will need to specify `--no-py`, `--no-json`, `--no-cpp`, etc, which makes the command a little bit messy.
- Output only if the desired file name is given.
  - The cons of this is that the default behavior is changed. If someone updated the dumper version without knowing this change while they grab all types of the output, their workflow breaks.
  - The other cons is that their command now looks messy. A workaround could be having a switch like `--output-all`.

**Comment by djkaty** [comment]
I'm aware of this problem, I'm also aware that outputting everything adds considerable time to the workflow so it is something I'd like to rectify, however the reason I haven't implemented such a change until now is exactly for the reasons you cited. My preferred approach is to only output when an output switch/name is specified (your second solution), but I just _know_ that users will file issues saying that the tool doesn't output anything. It is sort of sitting there in my todo list and I don't really know what to do about it honestly.

**Comment by RaenonX** [comment]
Yeah I agree that it may be not that important or having a high priority because it kinda *seldom* runs, but such a change could still be great IMO.

Considering the issues we both know, I think having a switch like `--no-output-all` and to specify what to output like `--json` could be a solution (let's say it's 3rd solution).

So the original commands won't break, since `--no-output-all` is not provided, all things should output.
In the case for the first one, it will be `--no-output-all` and `--cs` switches if I only want to grab the cs files.

**Comment by djkaty** [comment]
That's actually a really great solution, I like it. I'll get it implemented for you :)

**Comment by djkaty** [comment]
Other than the typo in the commit message that I'm too lazy to fix, this is now implemented, although I named the option `--select-outputs`. Let me know how you get on!

**Comment by RaenonX** [comment]
> Other than the typo in the commit message that I'm too lazy to fix, this is now implemented, although I named the option `--select-outputs`. Let me know how you get on!

Thanks for implementing such! May I grab the built exe like what you did previously?

**Comment by djkaty** [comment]
Oh right I forgot about that, hold on :)

**Comment by djkaty** [comment]
https://drive.google.com/file/d/1rkm84tOVqZLC9yNp305qV2C8DkP4vv2f/view?usp=sharing

Here you go! This is your last freebie, you need to set up your build environment now :)

**Comment by RaenonX** [comment]
Here's my usage running in `cmd`.

```cmd
Il2CppInspector ^
            --bin ../libil2cpp.so ^
            --metadata global-metadata.dat ^
            --select-outputs ^
            --cs-out ../Dumped ^
            --layout tree ^
            --suppress-metadata ^
            --separate-attributes
```

**Comment by djkaty** [comment]
I'll take that as a great success! Glad it works and thanks for the good suggestion 🙂
