### ISSUE TITLE
Improvements to C/C++ Scaffolding Generation

### ISSUE THREAD

**Issue by sc2ad** [djkaty/Il2CppInspector#129]
Hiya!

I've been around for a little while, but I'm only just stumbling on to this now, and let me start by saying that this is practically a gold mine! Thanks for all your hard work on this.

On a related note, I noticed you perform some form of C/C++ scaffolding generation and have at least a (little) experience making something that looks relatively reasonable. For example: https://github.com/sc2ad/BeatSaber-Quest-Codegen (you can see `include` which contains quite a few typedefs in as-close-to C++ as I could reasonably make) which contains a collection of auto-generated code from the (admittedly, poorly written) generator I wrote, available here: https://github.com/sc2ad/Il2Cpp-Modding-Codegen with absolutely no READMEs whatsoever... _sigh_

Anyways, I was wondering if you would be at least somewhat interested in a potential PR that would overhaul the scaffolding generation to look "more like" this, or at least as a standalone option. One of the main things currently stopping me from moving over to this is its lack of forward compatibility and the fact that it is so boilerplate-y. If I were to do anything, it'd be to add a ton of plugin functionality to the scaffolding generation so that I could make output similar to what my current code generation script does (which is a pain to maintain, and wasted effort that I feel could be shared elsewhere as well).

I'm happy to talk on Discord at `Sc2ad#8836` about more details/questions/concerns, as well as on this issue!

**Comment by djkaty** [comment]
Hey there :) I'm actually familiar (to a limited degree) with your work already, I believe I linked to one of your source files on Beatsaber-Hook in a recent tutorial blog as well. I've sent you a friend request (Katy) :)

**Comment by djkaty** [comment]
Closing - we'll talk it over on Discord :)
