### ISSUE TITLE
Unity internal class support such as Transform in the C++ DLL injection

### ISSUE THREAD

**Issue by SaboteurInCave** [djkaty/Il2CppInspector#130]
First of all, thank you very much for this project- it works as a charm!
I've had a small question about `il2cpp-types.h` generation process - is it possible to acuqire internal fields from the Unity class instances? 

```
struct Transform__Fields {
    struct Component_1__Fields _;
};

struct Component_1__Fields {
    struct Object_1__Fields _;
};

struct __declspec(align(8)) Object_1__Fields {
    void *m_CachedPtr;
};
```

As an example, I've taken a `Transform` class. According to the Unity documentation, it's possible to get the `position` property, but the generated file doesn't contain information about it.

So, am I missing something or is it impossible to get such of information?

**Comment by djkaty** [comment]
`position` is a property of Transform, not a field. Therefore you must use a property getter or setter method to access it, eg.

`Vector3 Transform_get_position(Transform *__this, MethodInfo *method);`

Hope that helps!
