### ISSUE TITLE
The Supplied Metadata file is not vaild.

### ISSUE THREAD

**Issue by ngoalong123** [djkaty/Il2CppInspector#132]
Hello Madam! I tried dump this file but it encrypted Metadata file. Can you try bypass it? thank you so much.
File: https://drive.google.com/file/d/17lxUzklJ5fydaT9V5e0ON6dgI-vP8bDv/view?usp=sharing

**Comment by djkaty** [comment]
The global-metadata.dat for this application is obfuscated and not supported by Il2CppInspector.

Il2CppInspector now includes a plugin architecture to enable 3rd party developers to implement loaders for obfuscated or encrypted workloads that are not supported directly. If you wish to, you can familiarize yourself with this and develop a plugin for the task. Documentation here: https://github.com/djkaty/Il2CppInspector/wiki/Plugins%3A-Getting-Started - examples here: https://github.com/djkaty/Il2CppInspectorPlugins. Feel free to submit your plugin to the plugins repo if you'd like it to be bundled with future releases.
