### ISSUE TITLE
Plugin system causes issues when using Il2CppInspector as a library

### ISSUE THREAD

**Issue by tech-ticks** [djkaty/Il2CppInspector#133]
Since the plugin system has been enabled permanently, it has become harder to use Il2CppInspector as a library because it will throw an exception if the plugin directory does not exist. While it would possible to download and unzip the required plugins in applications that use the library, there would be permission issues on applications installed in e.g. `Program Files` because the path is hardcoded relative to the location of the executable. As a first improvement, it would be great if it was possible to configure the plugin directory path to circumvent these file permission problems.

**Comment by djkaty** [comment]
You can disable the plugin system in a standalone application with:

`PluginManager.IsEnabled = false`

You can change the plugin folder with:

`PluginManager.Reload(string folderPath);`

Hope that addresses the issue :)
