### ISSUE TITLE
Crash on parallelization when using 1 hardware thread

### ISSUE THREAD

**Issue by ConsoleGaming** [djkaty/Il2CppInspector#134]
While exporting types.cs i'm keep getting this error message il2cpp inspector has encouterend a fatal error

**Comment by djkaty** [comment]
1. Make sure you are using the latest commit of Il2CppInspector
2. Make sure you have the latest set of plugins by using `get-plugins.ps1` or `get-plugins.sh`
3. Make sure all Il2CppInspector Core Plugins are enabled and all other plugins are disabled

4. We require the output from the Il2CppInspector CLI. Include the complete command line with all arguments and paste the entire output.
5. Attach `global-metadata.dat` and the IL2CPP binary to the issue.

**Comment by ConsoleGaming** [comment]
I tried it with mutiple games and the newest version of il2cpp inspector

**Comment by djkaty** [comment]
Still going to need to see the complete output as I'm unfortunately not a magician.

**Comment by ConsoleGaming** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/69332045/106746849-663b8f80-6623-11eb-8604-5765c941428f.png)

**Comment by djkaty** [comment]
What kind of CPU (processor) does your computer have? The exact model please :)

**Comment by ConsoleGaming** [comment]
![2021-02-03_14-02](https://user-images.githubusercontent.com/69332045/106750859-b1a46c80-6628-11eb-8af0-ebc652a6de87.png)

**Comment by djkaty** [comment]
Strange. The error you posted indicates Il2CppInspector can only find 1 core with 1 (hardware) thread on your system.

Are you running in a VM, docker container or similar?

When you open a command prompt and type:

```
echo %NUMBER_OF_PROCESSORS%
```

what number do you see?

**Comment by ConsoleGaming** [comment]
The output is 1 and I'm running windows 7 on a virtual machine called virtualbox

**Comment by djkaty** [comment]
How many cores/threads have you allocated to virtualbox? If 1, try changing it to 2 and let me know if that works.

If that is the case, I will make a bug fix for it.

**Comment by ConsoleGaming** [comment]
It works thanks 😁

**Comment by ConsoleGaming** [comment]
I changed to 2 just as you said

**Comment by djkaty** [comment]
Excellent! I'll create a fix so that Il2CppInspector works with 1 core/thread shortly.

**Comment by djkaty** [comment]
This bug is fixed in commit https://github.com/djkaty/Il2CppInspector/commit/297b3016f82595799bbd8cf8ffc8b201566df251. Thanks for your report!
