### ISSUE TITLE
Error on unpacking a game assembly

### ISSUE THREAD

**Issue by NOcturnais** [djkaty/Il2CppInspector#140]
**Sorry for my bad english**

I'm trying to "inspect" a game named PokeOne ([download here](https://www.pokeonecommunity.com/index.php?mod=files&action=listcat&where=28)).
It's a 32 bit game so I built a 32 bit version of IL2CppInspector but I get this error on unpacking GameAssembly.dll
![image](https://user-images.githubusercontent.com/32684737/107965894-6173c580-6fab-11eb-90ce-a89f9a3c04af.png)
You can try by yourself if u want

Here are the game files:
![image](https://user-images.githubusercontent.com/32684737/107966115-b0b9f600-6fab-11eb-8019-0934df192410.png)
![image](https://user-images.githubusercontent.com/32684737/107966134-b6afd700-6fab-11eb-9f13-c823509bd4a3.png)

**Comment by SamboyCoding** [comment]
You don't need to build a 32-bit version, the 64-bit version can handle 32-bit games just fine.

**Comment by SamboyCoding** [comment]
Ah, never mind, I'm not correct here.

**Comment by NOcturnais** [comment]
No I get this when I try to unpack with the 64bit version
![image](https://user-images.githubusercontent.com/32684737/107966856-b5cb7500-6fac-11eb-86d5-2b17897b0811.png)

**Comment by SamboyCoding** [comment]
Yeah I'm mistaken, don't mind me.

**Comment by NOcturnais** [comment]
oof ok x)

**Comment by djkaty** [comment]
Hey :) Am I supposed to install p1setup.exe? Just checking before I run a random exe file.

**Comment by NOcturnais** [comment]
It's a famous game you can check on youtube

**Comment by djkaty** [comment]
This issue is fixed in commit https://github.com/djkaty/Il2CppInspector/commit/55401a447ff2c478f37287d30fc24e036a131b45 - thanks for your bug report!
