### ISSUE TITLE
Specific apk is not supported

### ISSUE THREAD

**Issue by too-a** [djkaty/Il2CppInspector#143]
The app com.kakaogames.gdtskr doesn't open in lastest version of il2CppInspector.
Curiously, this app cannot use any other il2cpp dumper tool as the global-metadata.dat file does not exist inside apk and I also tested this developer's other apps that exists global-metadata.dat and it works fine.

Specifically, the following message is displayed when a file is selected.
![image](https://user-images.githubusercontent.com/78246843/108597795-34ba1680-73ce-11eb-9162-431bab59a6bf.png)
I tried to read the related code, but I couldn't figure out what's wrong with the apk.

+ Apk was obtained from ApkPure(xapk & Recompiled apk obtained after merge lib and base apk), apk-dl.

**Comment by djkaty** [comment]
Precise link to both the source APK and the recompiled version please :)

**Comment by too-a** [comment]
///LASTEST VERSION v2.10.1
+ https://apkcombo.com/ko-kr/apk-downloader/?q=com.kakaogames.gdtskr
+ https://apkpure.com/kr/%EA%B0%80%EB%94%94%EC%96%B8%ED%85%8C%EC%9D%BC%EC%A6%88/com.kakaogames.gdtskr
///RECOMPILED
+ https://www.dropbox.com/s/v9f1gxpm599ajye/com.kakaogames.gdtskr.apk?dl=0

thx

**Comment by djkaty** [comment]
This binary uses an obfuscated metadata loader that is not supported by Il2CppInspector.

You can find the load routine at virtual address 0x1B34110 in libil2cpp.so (il2cpp::vm::MetadataLoader::LoadMetadataFile) if you'd like to reverse engineer it yourself.

Il2CppInspector now includes a plugin architecture to enable 3rd party developers to implement loaders for obfuscated or encrypted workloads that are not supported directly. If you wish to, you can familiarize yourself with this and develop a plugin for the task. Documentation here: https://github.com/djkaty/Il2CppInspector/wiki/Plugins%3A-Getting-Started - examples here: https://github.com/djkaty/Il2CppInspectorPlugins. Feel free to submit your plugin to the plugins repo if you'd like it to be bundled with future releases.
