### ISSUE TITLE
Il2CppInspector not opening in Windows 7 ultimate 64bit version

### ISSUE THREAD

**Issue by jokerart06** [djkaty/Il2CppInspector#145]
i run this application version using this type of laptop version before and then i reformat my laptop. im using windows 7 ultimate 64bit version with installed framework 4.8 and run java application but when i download the new release exe of Il2CppInspector  and run the application , it didn't open even i run as administrator. i will send the picture of installed framework and other related exe. Did i miss something to install to run it properly? thanks for making this update
![windows 7 ultimate](https://user-images.githubusercontent.com/54529030/109418428-33b05880-797d-11eb-8c1d-205164e140be.PNG)

**Comment by djkaty** [comment]
Il2CppInspector is provided as a standalone exe with the .NET Core libraries statically linked, so you don't require any supporting apps or frameworks to be installed to use it.

Do the previous releases work on your newly formatted laptop?

**Comment by jokerart06** [comment]
> Il2CppInspector is provided as a standalone exe with the .NET Core libraries statically linked, so you don't require any supporting apps or frameworks to be installed to use it.
> 
> Do the previous releases work on your newly formatted laptop?

already resolve the issues when i try to install the visual studio 2019 and i think some netcore support the application. thank you. you can closed it now.
