### ISSUE TITLE
Mihoyo plugin fixes possible?

### ISSUE THREAD

**Issue by PythonLimited** [djkaty/Il2CppInspector#149]
Hi,
first of all: awesome stuff here :)

Now secondly, i have tinkered around with genshin impact for a while last year, but i just didnt knew about the IL2CPP architecture until i got my hands on an actual unity game this year which also used encryption in the global-metadata.

Now as it seems the mihoyo plugin would needed to be edited with every major release coming around judging from the plugin (i can see changes used for v1.1 to 1.2). And it also doesnt work on the versions i have 😢.

Is that process hard to do every time a new version comes out? Thats speaking from an android devs perspective, i usually expect libs to be decompileable with IDA, right out of the box :D. Are there any scripts that i could run to make this work on the latest version (1.4 official, have the 1.5 dev build atm...) and every time a new one comes out?

Best regards!

**Comment by PythonLimited** [comment]
EDIT: this can be ignored, i found out that using the UnityPlayer.dll from version 1.2 perfectly decrypts the 1.4+ global-metadata.dat and the UserAssembly.dll

My only question would be how i can export these decrypted dlls now?

**Comment by djkaty** [comment]
The DLLs aren't encrypted, they're obfuscated so you can't really do much about that.

As for how to update the plugin when they do change it, there are 3 functions you have to find, one for the metadata, one for the strings, one for the string literals. You can find an explanation for Honkai Impact which is more or less the same here: https://katyscode.wordpress.com/2021/01/17/reverse-engineering-adventures-honkai-impact-3rd-houkai-3-il2cpp-part-1/

You might also be interested in this scripting: https://katyscode.wordpress.com/2021/01/24/reverse-engineering-adventures-brute-force-function-search-or-how-to-crack-genshin-impact-with-powershell/

I would be delighted if someone could update the plugin when it's needed!

**Comment by PythonLimited** [comment]
Oh this is great. Very interesting article, will look into it.

**Comment by PythonLimited** [comment]
Apart from the debug info you can get with IL2CPP, is there a way to resolve the xrefs for the string in UserAssembly? Because i cant seem to find any for the most part. E.g. location 18c2c8e58 with string "Operation on non-blocking socket would block"

**Comment by djkaty** [comment]
You won't get direct address xrefs like that, string literals are addressed via their 'metadata usage' index, which is populated for the using method JIT with the internal GetStringLiteralFromIndex function; this is often inlined into the switch statement in InitializeMethodMetadata (or similar, I forget the exact function name). Suggest you refer to the il2cpp source code for the ugly details! :)

Is this issue ready to be closed, do you have what you need for the miHoYo stuff? I'd be most appreciative if you would be interested in keeping the plugin updated with PRs.

**Comment by PythonLimited** [comment]
> You won't get direct address xrefs like that, string literals are addressed via their 'metadata usage' index, which is populated for the using method JIT with the internal GetStringLiteralFromIndex function; this is often inlined into the switch statement in InitializeMethodMetadata (or similar, I forget the exact function name). Suggest you refer to the il2cpp source code for the ugly details! :)
> 
> Is this issue ready to be closed, do you have what you need for the miHoYo stuff? I'd be most appreciative if you would be interested in keeping the plugin updated with PRs.

Yes can be closed. We're already implementing logic for our private server and stuff :)
