### ISSUE TITLE
Issues compiling scaffolding generated from miHoYo games

### ISSUE THREAD

**Issue by flumf** [djkaty/Il2CppInspector#150]
Working with Genshin Impact version 1.2. UnityPlayer, global-metadata, and UserAssembly are all from the same version.
Target C++ compiler is MSVC, target Unity version is 2017.4.15 - 2017.4.40. No errors occur during export, and loading the project into Visual Studio (after retargeting) appears to function as expected.

Issues begin to arise after attempting to compile the scaffolding. Regardless of configuration used (I tried all 4), it immediately fails on il2cpp-api-functions.h. All errors seem to stem from issues with types being defined, which is odd because briefly looking through il2cpp-types.h shows that everything is (seemingly) in place.

Attached is a compilation log - if required I can send the project files as well.

[debug-x64-compile.log](https://github.com/djkaty/Il2CppInspector/files/6189859/debug-x64-compile.log)

**Comment by djkaty** [comment]
Looks weird in the log. Feel free to send over the project.

I should add that I'm not sure there is any point making scaffolding for Genshin Impact 1.2 because I think they prevent you from injecting DLLs on that version, although I'm not 100% sure on that - have you checked this?

**Comment by flumf** [comment]
Hey, thanks for the quick response!

Attaching the scaffolding project generated here. It hasn't been retargeted yet (or even opened in any IDE), so hopefully nothing is broken there.

With regards to injecting DLLs into Genshin, there's a few patches you can apply to UnityPlayer.dll that allow you to prevent the driver from starting - which allows you to inject dlls, dump global-metadata, and things of that nature without (ab)using libcapcom/csrss renaming. I don't have a list of the patches on hand, however I'll post them (if needed) once I dig them up again.

[tmp.zip](https://github.com/djkaty/Il2CppInspector/files/6194095/tmp.zip)

**Comment by djkaty** [comment]
Finally downloaded the project. I'm on hiatus til around mid-May so I'm gonna have to look into it then, sorry for the slowness.

I'd be very interested to see those patches if you're able to share :)

**Comment by flumf** [comment]
No worries about the hiatus, take your time.

Patches are attached, there's no guarantee that you'll be able to connect to actual servers since these will likely fail the file validation.

[patches.txt](https://github.com/djkaty/Il2CppInspector/files/6260224/patches.txt)

**Comment by jamescallen246** [comment]
Hi, sorry that this is a bit unrelated but could you also add saving the global-metadata.dat after it has been decrypted/deobfuscated? Only if you have the time. It only saves the encrypted version of it. Thank you

**Comment by DaedieGit** [comment]
> No worries about the hiatus, take your time.
> 
> Patches are attached, there's no guarantee that you'll be able to connect to actual servers since these will likely fail the file validation.
> 
> [patches.txt](https://github.com/djkaty/Il2CppInspector/files/6260224/patches.txt)

If you (or Katy) happen to still be interested in fixing this. The problem is actually a bug in the unity header. in file 24-2017.4.15-2017.4.40.h at line 1871.

**struct Il2CppDecimal
{
...
} Il2CppClass;**

should be

**struct Il2CppDecimal
{
...
};**

**Comment by flumf** [comment]
Ah, thank you! It seems that there's already a pull request for this (see #181), so hopefully Katy merges that when she gets a chance. I'll fix this locally and close this issue for now.
