### ISSUE TITLE
can you make tutorial?

### ISSUE THREAD

**Issue by PAYALzariya** [djkaty/Il2CppInspector#151]
hi, I am unable to know how I can build or make a .exe file. and how I can check source code or decompile .so or meta file.

can you please help me?

**Comment by djkaty** [comment]
https://bfy.tw/Qf1W

**Comment by AndnixSH** [comment]
This site is always useful XD

**Comment by djkaty** [comment]
Apparently not - he emailed me with the same question the day after I closed the issue.

Some people are just not cut out for this line of work.
