### ISSUE TITLE
2019.4.22 Error

### ISSUE THREAD

**Issue by ParrotInTheGarden** [djkaty/Il2CppInspector#154]
I can't use Il2cppinspector on an il2cpp game that was built in 2019.4.22 unity engine version, why is this happening?

**Comment by djkaty** [comment]
Impossible to know without:

- the input files
- any of the output
- any error message
- knowing which build you used
- which plugins you're using
- following the instructions in the issue filing template

Telepathy not my strong point, but probable duplicate of #148. Build from the latest commit and try again.

**Comment by ParrotInTheGarden** [comment]
![image](https://user-images.githubusercontent.com/80572092/114512780-248e1d00-9c42-11eb-9fed-c1ab321eda5f.png)
this is the error when i drag gameassembly.dll
