### ISSUE TITLE
More like a help

### ISSUE THREAD

**Issue by ParrotInTheGarden** [djkaty/Il2CppInspector#156]
is there a way to add code for a method (hook)
for example there is a method `addGems` that takes in `int ammount` as parameter and returns bool on success, i want to hook the method so every time it gets called i get the ammount printed on the console

**Comment by OsOmE1** [comment]
This is not a feature request for Il2CppInspector. I imagine you are using the dll injection project generated by Il2CppInspector in which case you can achieve this by using something like [MSDetours](https://github.com/microsoft/Detours) or if you want a different kind of hook(e.g. midhook/tramphook) you can either code it up yourself or check out something like [PolyHook](https://github.com/stevemk14ebr/PolyHook).

**Comment by ParrotInTheGarden** [comment]
thx :)
