### ISSUE TITLE
Could not process IL2CPP image

### ISSUE THREAD

**Issue by Miyuyami** [djkaty/Il2CppInspector#16]
Detected metadata version 24
Processed 609625 relocations
Container format: ELF
Container endianness: Little
Architecture word size: 32-bit
Instruction set: ARM
Global offset: 0x0000000000000000
Symbol table(s) found with 781 entries
No matches in symbol table
No matches via code heuristics
Could not process IL2CPP image

I've uploaded the libil2cpp.so and global-metadata.dat files: [files.zip](https://github.com/djkaty/Il2CppInspector/files/4113988/files.zip)

**Comment by djkaty** [comment]
Hey and thanks for your issue report. I checked out the binary file in a disassembler and it appears to be obfuscated so there is no automated way to find the required data unless you can first unpack/decrypt/deobfuscate the .so file. Sorry!

**Comment by djkaty** [comment]
Update: this file can actually be analysed successfully as of commit https://github.com/djkaty/Il2CppInspector/commit/5652e89abe763cf7956adf8b4f5d68a5f015121a !
