### ISSUE TITLE
IDA 7.5 Processing Types Syntax error

### ISSUE THREAD

**Issue by user23333** [djkaty/Il2CppInspector#160]
HeyRays version 7.5.0.201028 has been detected 
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>

Generated script file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
Processing Types
Error D:\temp\.\il2cpp.h:2361: Type 'Boolean' is already defined
Error D:\temp\.\il2cpp.h:6362: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:14024: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:14025: Syntax error near: }
Error D:\temp\.\il2cpp.h:32219: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:32220: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:32230: Syntax error near: }
Error D:\temp\.\il2cpp.h:32235: Undefined type name 'AppDomain__Fields'
Error D:\temp\.\il2cpp.h:32236: Syntax error near: }
Error D:\temp\.\il2cpp.h:129658: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:129687: Syntax error near: }
Error D:\temp\.\il2cpp.h:129692: Undefined type name 'HttpWebRequest__Fields'
Error D:\temp\.\il2cpp.h:129693: Syntax error near: }
Error D:\temp\.\il2cpp.h:129853: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:129854: Syntax error near: }
Error D:\temp\.\il2cpp.h:129859: Undefined type name 'WebConnectionGroup__Fields'
Error D:\temp\.\il2cpp.h:129860: Syntax error near: }
Error D:\temp\.\il2cpp.h:129940: Type 'EventHandler' is already defined
Error D:\temp\.\il2cpp.h:129960: Syntax error near: }
Error D:\temp\.\il2cpp.h:129965: Undefined type name 'WebConnection__Fields'
Processing method definitions
Syntax error near: AppDomain
SetType(0x18031eed0, 'void AppDomain__ctor(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85c0, 'AppDomainSetup * AppDomain_getSetup(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85c0, 'AppDomainSetup * AppDomain_get_SetupInformationNoCopy(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85d0, 'String * AppDomain_get_BaseDirectory(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c83b0, 'String * AppDomain_getFriendlyName(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c83b0, 'String * AppDomain_get_FriendlyName(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85a0, 'AppDomain * AppDomain_getCurDomain(MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85a0, 'AppDomain * AppDomain_get_CurrentDomain(MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7580, 'Assembly__Array * AppDomain_GetAssemblies(AppDomain * this, bool refOnly, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7590, 'Assembly__Array * AppDomain_GetAssemblies_1(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c75b0, 'Object * AppDomain_GetData(AppDomain * this, String * name, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1802e8bf0, 'Object * AppDomain_InitializeLifetimeService(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c79a0, 'Assembly * AppDomain_LoadAssembly(AppDomain * this, String * assemblyRef, Evidence * securityEvidence, bool refOnly, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7ab0, 'Assembly * AppDomain_Load(AppDomain * this, AssemblyName * assemblyRef, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c79b0, 'Assembly * AppDomain_LoadSatellite(AppDomain * this, AssemblyName * assemblyRef, bool throwOnError, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7ac0, 'Assembly * AppDomain_Load_1(AppDomain * this, AssemblyName * assemblyRef, Evidence * assemblySecurity, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8060, 'Assembly * AppDomain_Load_2(AppDomain * this, String * assemblyString, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8160, 'Assembly * AppDomain_Load_3(AppDomain * this, String * assemblyString, Evidence * assemblySecurity, bool refonly, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7780, 'AppDomain * AppDomain_InternalSetDomainByID(int32_t domain_id, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7790, 'AppDomain * AppDomain_InternalSetDomain(AppDomain * context, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7980, 'bool AppDomain_IsFinalizingForUnload(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c85b0, 'int32_t AppDomain_getDomainID(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c83b0, 'String * AppDomain_ToString(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c6dc0, 'void AppDomain_DoAssemblyLoad(AppDomain * this, Assembly * assembly, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c6e90, 'Assembly * AppDomain_DoAssemblyResolve(AppDomain * this, String * name, Assembly * requestingAssembly, bool refonly, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c72d0, 'Assembly * AppDomain_DoTypeResolve(AppDomain * this, Object * name_or_tb, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c71a0, 'Assembly * AppDomain_DoResourceResolve(AppDomain * this, String * name, Assembly * requesting, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c7180, 'void AppDomain_DoDomainUnload(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c75c0, 'Byte__Array * AppDomain_GetMarshalledDomainObjRef(AppDomain * this, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8280, 'void AppDomain_ProcessMessageInDomain(AppDomain * this, Byte__Array * arrRequest, CADMethodCallMessage * cadMsg, Byte__Array * * arrResponse, CADMethodReturnMessage * * cadMrm, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c83c0, 'void AppDomain_add_DomainUnload(AppDomain * this, EventHandler * value, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8600, 'void AppDomain_remove_DomainUnload(AppDomain * this, EventHandler * value, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8460, 'void AppDomain_add_ProcessExit(AppDomain * this, EventHandler * value, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c86a0, 'void AppDomain_remove_ProcessExit(AppDomain * this, EventHandler * value, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8500, 'void AppDomain_add_UnhandledException(AppDomain * this, UnhandledExceptionEventHandler * value, MethodInfo * method);') failed!
Syntax error near: AppDomain
SetType(0x1813c8740, 'void AppDomain_remove_UnhandledException(AppDomain * this, UnhandledExceptionEventHandler * value, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_OperationType__Enum
SetType(0x18103f430, 'Task_1_System_Int32_ * MobileAuthenticatedStream_StartOperation(MobileAuthenticatedStream * this, MobileAuthenticatedStream_OperationType__Enum type, AsyncProtocolRequest * asyncRequest, CancellationToken cancellationToken, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_ProcessAuthentication_d_47__Boxed
SetType(0x1801b69b0, 'void MobileAuthenticatedStream_ProcessAuthentication_d_47_MoveNext(MobileAuthenticatedStream_ProcessAuthentication_d_47__Boxed * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_ProcessAuthentication_d_47__Boxed
SetType(0x1800eaae0, 'void MobileAuthenticatedStream_ProcessAuthentication_d_47_SetStateMachine(MobileAuthenticatedStream_ProcessAuthentication_d_47__Boxed * this, IAsyncStateMachine * stateMachine, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_StartOperation_d_58__Boxed
SetType(0x1801b6a30, 'void MobileAuthenticatedStream_StartOperation_d_58_MoveNext(MobileAuthenticatedStream_StartOperation_d_58__Boxed * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_StartOperation_d_58__Boxed
SetType(0x1801b6a40, 'void MobileAuthenticatedStream_StartOperation_d_58_SetStateMachine(MobileAuthenticatedStream_StartOperation_d_58__Boxed * this, IAsyncStateMachine * stateMachine, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_c_DisplayClass66_0
SetType(0x18031eed0, 'void MobileAuthenticatedStream_c_DisplayClass66_0__ctor(MobileAuthenticatedStream_c_DisplayClass66_0 * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_c_DisplayClass66_0
SetType(0x181044e80, 'int32_t MobileAuthenticatedStream_c_DisplayClass66_0__InnerRead_b__0(MobileAuthenticatedStream_c_DisplayClass66_0 * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_InnerRead_d_66__Boxed
SetType(0x1801b6940, 'void MobileAuthenticatedStream_InnerRead_d_66_MoveNext(MobileAuthenticatedStream_InnerRead_d_66__Boxed * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_InnerRead_d_66__Boxed
SetType(0x1801b6950, 'void MobileAuthenticatedStream_InnerRead_d_66_SetStateMachine(MobileAuthenticatedStream_InnerRead_d_66__Boxed * this, IAsyncStateMachine * stateMachine, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_InnerWrite_d_67__Boxed
SetType(0x1801b69a0, 'void MobileAuthenticatedStream_InnerWrite_d_67_MoveNext(MobileAuthenticatedStream_InnerWrite_d_67__Boxed * this, MethodInfo * method);') failed!
Syntax error near: MobileAuthenticatedStream_InnerWrite_d_67__Boxed
SetType(0x1800eaae0, 'void MobileAuthenticatedStream_InnerWrite_d_67_SetStateMachine(MobileAuthenticatedStream_InnerWrite_d_67__Boxed * this, IAsyncStateMachine * stateMachine, MethodInfo * method);') failed!
Syntax error near: HttpWebRequest
SetType(0x1802f7b20, 'HttpWebRequest * MonoTlsStream_get_Request(MonoTlsStream * this, MethodInfo * method);') failed!
Syntax error near: HttpWebRequest
SetType(0x1810418a0, 'void MonoTlsStream__ctor(MonoTlsStream * this, HttpWebRequest * request, NetworkStream * networkStream, MethodInfo * method);') failed!
Syntax error near: CallbackHelpers_c_DisplayClass5_0
SetType(0x18031eed0, 'void CallbackHelpers_c_DisplayClass5_0__ctor(CallbackHelpers_c_DisplayClass5_0 * this, MethodInfo * method);') failed!
Syntax error near: CallbackHelpers_c_DisplayClass5_0
SetType(0x181044e50, 'bool CallbackHelpers_c_DisplayClass5_0__MonoToPublic_b__0(CallbackHelpers_c_DisplayClass5_0 * this, Object * t, X509Certificate_1 * c, X509Chain * ch, SslPolicyErrors__Enum e, MethodInfo * method);') failed!
Syntax error near: CallbackHelpers_c_DisplayClass8_0
SetType(0x18031eed0, 'void CallbackHelpers_c_DisplayClass8_0__ctor(CallbackHelpers_c_DisplayClass8_0 * this, MethodInfo * method);') failed!
Syntax error near: CallbackHelpers_c_DisplayClass8_0
SetType(0x181044ee0, 'X509Certificate_1 * CallbackHelpers_c_DisplayClass8_0__MonoToInternal_b__0(CallbackHelpers_c_DisplayClass8_0 * this, String * t, X509CertificateCollection_2 * lc, X509Certificate_1 * rc, String__Array * ai, MethodInfo * method);') failed!
Syntax error near: NtlmSession
SetType(0x18031eed0, 'void NtlmSession__ctor(NtlmSession * this, MethodInfo * method);') failed!
Syntax error near: Authorization
SetType(0x181042430, 'Authorization * NtlmSession_Authenticate(NtlmSession * this, String * challenge, WebRequest * webRequest, ICredentials * credentials, MethodInfo * method);') failed!
Syntax error near: Authorization
SetType(0x181042000, 'Authorization * NtlmClient_Authenticate(NtlmClient * this, String * challenge, WebRequest * webRequest, ICredentials * credentials, MethodInfo * method);') failed!
Syntax error near: Authorization
SetType(0x1802e8bf0, 'Authorization * NtlmClient_PreAuthenticate(NtlmClient * this, WebRequest * webRequest, ICredentials * credentials, MethodInfo * method);') failed!
Syntax error near: NtlmClient
SetType(0x181042400, 'String * NtlmClient_get_AuthenticationType(NtlmClient * this, MethodInfo * method);') failed!
Syntax error near: NtlmClient
SetType(0x18031eed0, 'void NtlmClient__ctor(NtlmClient * this, MethodInfo * method);') failed!
Syntax error near: NtlmClient_c
SetType(0x18031eed0, 'void NtlmClient_c__ctor(NtlmClient_c * this, MethodInfo * method);') failed!
Syntax error near: NtlmSession
SetType(0x181044ac0, 'NtlmSession * NtlmClient_c__Authenticate_b__1_0(NtlmClient_c * this, HttpWebRequest * x, MethodInfo * method);') failed!
Syntax error near: SafeProcessHandle
SetType(0x181041c10, 'bool NativeMethods_DuplicateHandle_1(HandleRef hSourceProcessHandle, HandleRef hSourceHandle, HandleRef hTargetProcess, SafeProcessHandle * * targetHandle, int32_t dwDesiredAccess, bool bInheritHandle, int32_t dwOptions, MethodInfo * method);') failed!
Syntax error near: SafeProcessHandle
SetType(0x181041d90, 'bool NativeMethods_GetExitCodeProcess_1(SafeProcessHandle * processHandle, int32_t * exitCode, MethodInfo * method);') failed!
Syntax error near: SafeProcessHandle
SetType(0x181042940, 'void SafeProcessHandle__ctor(SafeProcessHandle * this, void * handle, MethodInfo * method);') failed!
Syntax error near: SafeProcessHandle
SetType(0x181042910, 'void SafeProcessHandle__ctor_1(SafeProcessHandle * this, void * existingHandle, bool ownsHandle, MethodInfo * method);') failed!
Syntax error near: SafeProcessHandle
SetType(0x181042890, 'bool SafeProcessHandle_ReleaseHandle(SafeProcessHandle * this, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e23e0, 'void UriBuilder__ctor(UriBuilder * this, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e2260, 'void UriBuilder__ctor_1(UriBuilder * this, Uri_1 * uri, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e17a0, 'void UriBuilder_Init(UriBuilder * this, Uri_1 * uri, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e25b0, 'void UriBuilder_set_Host(UriBuilder * this, String * value, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e2680, 'void UriBuilder_set_Path(UriBuilder * this, String * value, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e2730, 'void UriBuilder_set_Query(UriBuilder * this, String * value, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e27d0, 'void UriBuilder_set_Scheme(UriBuilder * this, String * value, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e2510, 'Uri_1 * UriBuilder_get_Uri(UriBuilder * this, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e1700, 'bool UriBuilder_Equals(UriBuilder * this, Object * rparam, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e1770, 'int32_t UriBuilder_GetHashCode(UriBuilder * this, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e1980, 'void UriBuilder_SetFieldsFromUri(UriBuilder * this, Uri_1 * uri, MethodInfo * method);') failed!
Syntax error near: UriBuilder
SetType(0x1820e1b40, 'String * UriBuilder_ToString(UriBuilder * this, MethodInfo * method);') failed!
Syntax error near: InvariantComparer
SetType(0x1813f57a0, 'void InvariantComparer__ctor(InvariantComparer * this, MethodInfo * method);') failed!
Syntax error near: InvariantComparer
SetType(0x1813f55e0, 'int32_t InvariantComparer_Compare(InvariantComparer * this, Object * a, Object * b, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x18135d520, 'ParsingError__Enum Uri_1_GetCombinedString(Uri_1 * baseUri, String * relativeStr, bool dontEscape, String * * result, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x18135dd40, 'UriFormatException * Uri_1_GetException(ParsingError__Enum err, MethodInfo * method);') failed!
Syntax error near: UriHostNameType__Enum
SetType(0x181366460, 'UriHostNameType__Enum Uri_1_get_HostNameType(Uri_1 * this, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x181362230, 'ParsingError__Enum Uri_1_ParseScheme(String * uriString, Uri_Flags__Enum * flags, UriParser * * syntax, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x181362440, 'ParsingError__Enum Uri_1_PrivateParseMinimal(Uri_1 * this, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x181361d30, 'uint16_t Uri_1_ParseSchemeCheckImplicitFile(uint16_t * uriString, uint16_t length, ParsingError__Enum * err, Uri_Flags__Enum * flags, UriParser * * syntax, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x181359a80, 'ParsingError__Enum Uri_1_CheckSchemeSyntax(uint16_t * ptr, uint16_t length, UriParser * * syntax, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x181357b30, 'uint16_t Uri_1_CheckAuthorityHelper(Uri_1 * this, uint16_t * pString, uint16_t idx, uint16_t length, ParsingError__Enum * err, Uri_Flags__Enum * flags, UriParser * syntax, String * * newHost, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x1813575d0, 'void Uri_1_CheckAuthorityHelperHandleDnsIri(Uri_1 * this, uint16_t * pString, uint16_t start, int32_t end, int32_t startInput, bool iriParsing, bool hasUnicode, UriParser * syntax, String * userInfoString, Uri_Flags__Enum * flags, bool * justNormalized, String * * newHost, ParsingError__Enum * err, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x1813572f0, 'void Uri_1_CheckAuthorityHelperHandleAnyHostIri(Uri_1 * this, uint16_t * pString, int32_t startInput, int32_t end, bool iriParsing, bool hasUnicode, UriParser * syntax, Uri_Flags__Enum * flags, String * * newHost, ParsingError__Enum * err, MethodInfo * method);') failed!
Syntax error near: Uri_Check__Enum
SetType(0x181358b80, 'Uri_Check__Enum Uri_1_CheckCanonical(Uri_1 * this, uint16_t * str, uint16_t * idx, uint16_t end, uint16_t delim, MethodInfo * method);') failed!
Syntax error near: ParsingError__Enum
SetType(0x18135fcf0, 'void Uri_1_InitializeUri(Uri_1 * this, ParsingError__Enum err, UriKind__Enum uriKind, UriFormatException * * e, MethodInfo * method);') failed!
Syntax error near: UnescapeMode__Enum
SetType(0x1820e3b60, 'Char__Array * UriHelper_UnescapeString(String * input, int32_t start, int32_t end, Char__Array * dest, int32_t * destPosition, uint16_t rsvd1, uint16_t rsvd2, uint16_t rsvd3, UnescapeMode__Enum unescapeMode, UriParser * syntax, bool isQuery, MethodInfo * method);') failed!
Syntax error near: UnescapeMode__Enum
SetType(0x1820e3c40, 'Char__Array * UriHelper_UnescapeString_1(uint16_t * pStr, int32_t start, int32_t end, Char__Array * dest, int32_t * destPosition, uint16_t rsvd1, uint16_t rsvd2, uint16_t rsvd3, UnescapeMode__Enum unescapeMode, UriParser * syntax, bool isQuery, MethodInfo * method);') failed!
Syntax error near: UriParser_BuiltInUriParser

**Comment by djkaty** [comment]
Did you solve the problem?

**Comment by kOchirasu** [comment]
I had the same problem and it seems to be a naming conflict for `Boolean` and `EventHandler` I added a suffix to them and can run the script properly.
