### ISSUE TITLE
Add option to only parse global-metadata file.

### ISSUE THREAD

**Issue by PappaPaj** [djkaty/Il2CppInspector#165]
I'm working with a web assembly Web GL game where the binary is not supported, however, I have managed to extract the global metadata. Would just like to parse this metadata file and view functions without needing to pass a binary.

**Comment by djkaty** [comment]
Hey, I don't have any plans to add this feature but I'm coming back off my hiatus shortly and WebAssembly binary support is on the roadmap for the 2021.2 release later this year. I know that doesn't help you right now, so you may want to look at Il2CppDumper which does support WebAssembly. Hope that helps!

**Comment by PappaPaj** [comment]
Sounds good, thanks for pointing me towards that IL2CppDumper, been completely in the dark with this web assembly game for almost a year. Would love to see more tooling be developed for web assembly, 

Great write-up for manipulating Unity WASM games - https://ctftime.org/writeup/24789
