### ISSUE TITLE
Question about il2cpp-functions.h content

### ISSUE THREAD

**Issue by Cr4nkSt4r** [djkaty/Il2CppInspector#172]
I have one short question,
is there a setting to get the old il2cpp-functions.h method content like _ScrollableArea_____________34_ instead of _ScrollableArea_u0927u091Eu0925u0924u0920u0926u0926u0929u091Cu0929u0920_?

It was much nicer to work with. 
Or can this be done plugin wise? If so, is there an existing one?

kind regards

**Comment by OsOmE1** [comment]
Hello Crassmaker, yes this can be done with plugins and if my eyes don't deceive me this is phasmaphobia obfuscation by Beebyte in that case you can use [Beebyte-Deobfuscator](https://github.com/OsOmE1/Beebyte-Deobfuscator) with the correct settings as listed in the README, and it should do some work for you. Otherwise, you can write your own plugin using [Il2CppInspectorPlugins](https://github.com/djkaty/Il2CppInspectorPlugins)'s examples as your guide.

**Comment by Cr4nkSt4r** [comment]
Yea, I tried your plugin, but it never worked for me, sadly.
Prob. missing an unobfuscated GameAssemlby.dll, because when they switched to il2cpp, they also started obfuscating.
I even thought about changing the source of inspector, to mimic its old behaviour, but I don't think, this is worth the hussle.
I prob. just do some settings wrong and the problem is on my side.

**Comment by Cr4nkSt4r** [comment]
To post the solution, maybe for others:
`public static string ToCIdentifier(this string str, bool allowScopeQualifiers = false) {
            str = Regex.Replace(str, "[^a-zA-Z0-9_]", "_");
            if (!Regex.IsMatch(str, "^[a-zA-Z_]"))
                str = "_" + str;
            return str;
        }`

**Comment by SamboyCoding** [comment]
For what it's worth, you missed it, there is an option to run the beebyte deobfuscator with an old mono folder and a current il2cpp build.

**Comment by djkaty** [comment]
Besides unnecessarily removing the pointer and scope qualifier munges, this solution will break as soon as you encounter two identifiers that are the same besides their Unicode characters. That's why it is the way it is currently, to ensure uniqueness.

**Comment by djkaty** [comment]
Follow on: I think the correct away is probably to override the virtual getter for `Name` in `CppFnPtrType` in `Cpp\CppType.cs` if you want to customize the output;  or to keep to the behaviour clear, add a new method like GetSanitizedName() to the `CppFnPtrType` that returns a modification of `Name` to your liking.

**Comment by Cr4nkSt4r** [comment]
Thanks for clarification!

**Comment by Cr4nkSt4r** [comment]
> For what it's worth, you missed it, there is an option to run the beebyte deobfuscator with an old mono folder and a current il2cpp build.

How do I do this? I mean, I don't need it anymore, but it would be nice to know, because I can only choose il2cpp OR mono.
kind regards
