### ISSUE TITLE
XOR decryptor encountered an error while executing PostProcessMetadata: Unable to read beyond the end of the stream 

### ISSUE THREAD

**Issue by muathudaudon** [djkaty/Il2CppInspector#176]
NO WORKING FOR NEW VERSION CALL OF DUTY MOBILE BRO
PLEASE FIX THANKSSSSSSSSSSS
https://drive.google.com/file/d/1cNKtEIguhgTvPQiOoBl88vseXw9g789L/view?usp=sharing

**Comment by hgreal** [comment]
You could have at least asked it politely and without caps...

**Comment by djkaty** [comment]
You should see the emails and blog comments I get.

It's no wonder most hackers don't make their tools public anymore.

**Comment by muathudaudon** [comment]
How to fix katy...pl teach me 👌👌👌

Vào 08:25, T.2, 2 Th8, 2021 Katy ***@***.***> đã viết:
