### ISSUE TITLE
Don't Work With DLL Files

### ISSUE THREAD

**Issue by mendax47** [djkaty/Il2CppInspector#23]
IL2CPPDumper Can easily Dump This But IL2CPPInspector Failed

IL2CPPInspector
![1](https://user-images.githubusercontent.com/6140928/75106418-9c684500-5646-11ea-9cf2-6331662017d9.PNG)

IL2CPPDumper
![2](https://user-images.githubusercontent.com/6140928/75106425-b144d880-5646-11ea-97a7-aabffe5d5b10.PNG)

**Comment by djkaty** [comment]
Hey, thanks for your bug report! Please attach the DLL and global-metadata.dat file to the issue so that I can investigate the problem. Thanks!

**Comment by mendax47** [comment]
https://drive.google.com/file/d/1SXf4SEK3ZVj1eJvxrFmu9IZgQu39QdEr/view?usp=sharing

**Comment by djkaty** [comment]
This issue is fixed in commit https://github.com/djkaty/Il2CppInspector/commit/8bdea7780bd32cc13170b506c5194f438db5e99b . Thanks for your help!
