### ISSUE TITLE
an item with the same key has already been added Key.

### ISSUE THREAD

**Issue by warleyc** [djkaty/Il2CppInspector#26]
Hi,

I used the last version of  Il2CppInspector and after open the file libil2cp.so the error message is display.  : 
something went wrong! an item with the same key has already been added Key.

files  

https://drive.google.com/open?id=1NMVFfutCrL8NG7K-juWMorlYVzUYQYKp
https://drive.google.com/open?id=1gN_Mac3UfjJ46Ip0Rjkwb-gx3GMTa2ml
https://drive.google.com/open?id=1wjKmzJWdm425CXB6j1ln8w7oUkqJfCQ2

**Comment by djkaty** [comment]
Thank you for your bug report! My schedule is an absolute circus right now because of covid-19 but I will do my best to help you as soon as possible :)

**Comment by warleyc** [comment]
I updated the link.
take care of yourself.

**Comment by djkaty** [comment]
Very quick note: planning to get back to working on Il2CppInspector in June, hopefully my schedule has calmed down then :)

**Comment by djkaty** [comment]
Good news and bad news I'm afraid.

The good news is there was a bug in the ELF handling which I was able to fix. The bad news is this won't help you much; the file you supplied is either compressed or packed/encrypted (or both); the first two thirds are more or less all-zero and the last third is unstructured data, leading me to believe it's packed or obfuscated in some way.

Sorry I couldn't be more helpful, but thank you for giving me the opportunity to fix the other bug!
