### ISSUE TITLE
Unable to load a certain libil2cpp.so

### ISSUE THREAD

**Issue by cra0kalo** [djkaty/Il2CppInspector#27]
It might be packed, but here are the sample files
https://drive.google.com/open?id=1gG-txil4fOj0cb_yMuFGQDXbEOlEFXKo

djkaty can you have a quick look for me please I appreciate it.

**Comment by djkaty** [comment]
Hey! Thank you for sending this, unfortunately my schedule is all over the place due to the current global health situation, but I've downloaded the files and will look at them when I can. Sorry for the delay.

**Comment by cra0kalo** [comment]
Alll good thank you djkaty! Stay safe

**Comment by djkaty** [comment]
Very quick note: planning to get back to working on Il2CppInspector in June, hopefully my schedule has calmed down then :)

**Comment by djkaty** [comment]
This issue is fixed in commit https://github.com/djkaty/Il2CppInspector/commit/370eebfffcc4270afa3e2c4759b3051fcbdf77a4 - thanks for your help! Let me know if you have any further problems.
