### ISSUE TITLE
ios ((Payload/(appname).app/Frameworks/UnityFramework.framework/UnityFramework))

### ISSUE THREAD

**Issue by Avatarchik** [djkaty/Il2CppInspector#33]
Hi! How can i dump ios?
ipa file: https://drive.google.com/open?id=1UPCPLTCqYHYODJPg6PhYXPG1wxe__3tX

**Comment by djkaty** [comment]
You need to extract the (decrypted) binary file and global-metadata.dat from the IPA file and use them as inputs to Il2CppInspector :)
