### ISSUE TITLE
Tests fail in latest master

### ISSUE THREAD

**Issue by nneonneo** [djkaty/Il2CppInspector#40]
The latest patch splits built binaries into ARMv7 and ARM64 variants, causing `TestGenericTypes` (TestGenerics.cs) and `TestNames` (TestNames.cs) to fail with `System.IO.DirectoryNotFoundException` errors.

It also doesn't come with expected results for any of the ARMv7 or ARM64 binaries.

To reproduce: delete `Il2CppTests\TestBinaries`, run `generate-binaries.ps1`, `generate-tests.ps1`, then run all tests. Observe many tests fail; expected result is that all tests pass.

**Comment by djkaty** [comment]
Forgot to add the files to source control 😂 

Fixed in https://github.com/djkaty/Il2CppInspector/commit/b87d82fd11afedf4f45201de152db5b2a132d21c
