### ISSUE TITLE
Ghidra script generation

### ISSUE THREAD

**Issue by MunWolf** [djkaty/Il2CppInspector#42]
I noticed you have a IDAPython script generator but not a Ghidra one,
as Ghidra is open source I feel it would be great to add a similar one for it.

I may work on adding this myself and doing a PR if I have the time, but wanted to put this here for visabilities sake.

**Comment by djkaty** [comment]
I've been meaning to check out Ghidra for general but it's something I haven't had the time to get around to yet.

I'd be delighted to incorporate Ghidra support but I have no idea how to write scripts for it so if you are able to make a PR that would be awesome. You can use the `Outputs/IDAPythonScript.cs` file as a starting point.

If the Ghidra script is very similar to the IDAPython version, I would recommend renaming that class to ''DisassemblerScript.cs' and adding an enum to select the disassembler type. If they are substantially different, copy the existing file to `GhidraScript.cs` and re-write as necessary.

Will leave the issue open til this gets resolved one way or another!

**Comment by djkaty** [comment]
Hey @MunWolf !

The latest commit of Il2CppInspector includes full (but experimental) Ghidra support via both the CLI and GUI for all of the supported file formats. As well as names and labels it will also provide C++ and IL types and function prototypes wherever applicable, including for generic methods, custom attribute generators, Method.Invoke thinks and so on, as with the existing IDA Python script output.

To specify the script should be for Ghidra, use `-a Ghidra` (case-sensitive) at the command-line, or select Ghidra from the script target drop-down box in the GUI.

You need to load the data into Ghidra in two steps:
1. File -> Parse C Source... and make a profile with the header file generated by Il2CppInspector (this is `cpp/appdata/il2cpp-types.h` by default at the CLI, or the name of the `.py` file with an `.h` extension instead by default in the GUI). Set the following parse option:

`-D_GHIDRA_`

2. Use the Script Manager to add the folder with the generated script as a script folder, then refresh the view and run the Python script.

I will write a full detailed tutorial on the exact steps for all this in the README.md file later.

I have tested this a fair bit and fixed a lot of bugs but I'd really like a Ghidra user's feedback on this if you could take a bit to look at it!

**Comment by MunWolf** [comment]
Very nice!
I will have a look at it once I have the time, thank you very much for the hard work.

**Comment by djkaty** [comment]
I've been using this for a few days now for real work and haven't experienced any problems so I'm going to go ahead and close the issue and consider Ghidra support implemented. If there are any problems feel free to open a new issue!
