### ISSUE TITLE
Radare2 script generation

### ISSUE THREAD

**Issue by BowDown097** [djkaty/Il2CppInspector#45]
I've recently looked into Cutter, which is an incredibly promising reverse engineering tool compared to IDA. Considering moving to it but no il2cpp tool has support for generating radare2 scripts. 

The devs made a script that converts IDA scripts to radare2 ones but saying it's terrible is an understatement (running it on Bloons TD 6 it literally used 20+ gb of ram before crashing). Would be really cool to see it get support!

**Comment by djkaty** [comment]
Sweet mother of Hades, the syntax for Radare2 looks absolutely horrendous. Can you point me to the script that converts IDAPython to r2? I was only able to find one for IDC scripts. If I can get the converter to work on a small example I'll be happy to integrate it.

**Comment by BowDown097** [comment]
Oh, my bad! Ya it does appear to only be for IDB/IDC, I was mistaken.

**Comment by djkaty** [comment]
That's probably why it used 20GB and crashed then 😂 

I have a lot of other features I want to implement into Il2CppInspector, but I'll leave this issue open to gauge demand or in case anyone else wants to tackle it.

**Comment by djkaty** [comment]
The latest commit of Il2CppInspector includes a simplified way to add new script targets.

To add support for a new application such as Radare2, you need to create a Python script in Il2CppInspector/Outputs/ScriptResources/Targets which implements a set of functions.

You can see working examples in the `IDA.py` and `Ghidra.py` scripts with implementations of all the required functions.

The shared code is in `shared-main.py`. These and some other bits and pieces get concatenated together (in `Pythonscript.cs`) to produce the final script.

The Python file must be included in the project as an Embedded Resource. Once this is done, it will appear automatically as a target in the drop-down box in the GUI, and as a valid option to the new `-t` argument in the CLI which specifies the script target to create.

I hope this helps make the task easier as you now only need to code one script in Python and can ignore everything else. If you manage to get it working or have any questions please let me know :)

**Comment by djkaty** [comment]
Closing - tooling is provided to make custom Python targets as outlined above.
