### ISSUE TITLE
Doesn't build for MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by ikuskov** [djkaty/Il2CppInspector#46]
Hi, 

I am using MacOS 10.15.5 (Catalina). When I am trying to build it trows following error:

```
$ dotnet publish -r osx.10.15-x64 -c Release
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/local/share/dotnet/sdk/3.1.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1100: Windows is required to build Windows desktop applications. [Il2CppInspector/Il2CppInspector.GUI/Il2CppInspector.GUI.csproj]
```

I have also tried to build with `dotnet publish -r osx-x64 -c Release`, it had same effect. 

Thanks!

**Comment by ikuskov** [comment]
Note: I am not very familiar with .NET, so are not going to make a PR. 
I just got it working for me, if you know how these configs interact with the project please make a proper PR ^_^.

I was able to build CLI tool by doing following:
* Update Il2CppInspector.CLI.csproj:
```
-    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
+    <RuntimeIdentifiers>win-x64;osx.10.15-x64</RuntimeIdentifiers>
```
* Build only CLI tool:
```
$ cd Il2CppInspector.CLI
$ dotnet publish -r osx.10.15-x64 -c Release
```

**Comment by vivalavladislav** [comment]
@ikuskov I was able to build CLI for MacOS 10.14 but can't run it. Getting these errors 
```
bash ./Il2CppInspector
./Il2CppInspector: ./Il2CppInspector: cannot execute binary file
```

**Comment by djkaty** [comment]
Thanks for the reports guys. I don't have access to a Mac but I was able to reproduce the same effect on Linux.

@ikuskov if you build the CLI tool using the command:

```
cd Il2CppInspector.CLI
dotnet publish -r osx-x64 -c Release
```
(note `osx-x64` without a version number), and **without** changing Il2CppInspector.CLI.csproj, does that work for you?

I was able to build the CLI tool in Linux this way using `-r linux-x64` without making any changes to the project files.

@vivalavladislav Make sure you specify a RID with the -r flag so that dotnet builds the correct binary type for your platform. If you don't specify a flag, it defaults to win-x64, which will obviously not run on a Mac.

**Comment by vivalavladislav** [comment]
@djkaty hey thanks for the answer. In case I don't specify the `-r` argument the build doesn't happen at all. When I do specify -r, the build happens and the binary file is created. Just when I try executing it I get an error.
Here's the dump from Terminal
```

Mystics-Confidential:Il2CppInspector.CLI vladsviatetskyi$ dotnet publish -c Release -r osx-x64
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 43.92 ms for /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.Common/Il2CppInspector.csproj.
  Restore completed in 43.92 ms for /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/Il2CppInspector.CLI.csproj.
  Restore completed in 43.92 ms for /Users/vladsviatetskyi/Proto/Il2CppInspector/Bin2Object/Bin2Object/Bin2Object.csproj.
  Restore completed in 44.21 ms for /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/Il2CppInspector.CLI.csproj.
  Restore completed in 43.95 ms for /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/Il2CppInspector.CLI.csproj.
  Bin2Object -> /Users/vladsviatetskyi/Proto/Il2CppInspector/Bin2Object/Bin2Object/bin/Release/netstandard2.1/osx-x64/Bin2Object.dll
  Bin2Object -> /Users/vladsviatetskyi/Proto/Il2CppInspector/Bin2Object/Bin2Object/bin/Release/netstandard2.1/Bin2Object.dll
  Il2CppInspector -> /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.Common/bin/Release/netstandard2.1/Il2CppInspector.Common.dll
  Il2CppInspector.CLI -> /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/osx-x64/Il2CppInspector.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Il2CppInspector.CLI -> /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/osx-x64/publish/
Mystics-Confidential:Il2CppInspector.CLI vladsviatetskyi$ cd /Users/vladsviatetskyi/Proto/Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/osx-x64/publish/
Mystics-Confidential:publish vladsviatetskyi$ bash ./Il2CppInspector
./Il2CppInspector: ./Il2CppInspector: cannot execute binary file
Mystics-Confidential:publish vladsviatetskyi$ 
```

**Comment by djkaty** [comment]
I assume you have permission to execute the binary? (`chmod +x Il2CppInspector`)
What happens when you omit `bash` from the start of the command?

I'm sort of shooting in the dark here because I know virtually nothing about MacOS X.

**Comment by vivalavladislav** [comment]
A combination of that worked: got it running now. Thanks!

**Comment by ikuskov** [comment]
@djkaty can confirm it works without modifying the project file! Silly of me to not try it first :D Command that worked after I revert my changes:
```
$ cd Il2CppInspector.CLI/
$ dotnet publish -r osx-x64 -c Release
```

Thank you for the suggestion!

**Comment by djkaty** [comment]
@ikuskov That's awesome.

Thank you both, what I will do is update the README.md to make it clear that the GUI version only compiles for Windows, and provide explicit RIDs and `cd` instruction lines for the MacOS and Linux builds!

**Comment by djkaty** [comment]
I've updated the build instructions in the README to hopefully be correct for OS X and Linux.

Thank you for your help both!

**Comment by BlueFalconHD** [comment]
Anyone have prebuilt OS X??

**Comment by nandlab** [comment]
On Linux, even if I type `dotnet publish -r linux-x64 -c Release` I get:
`error NETSDK1100: Windows is required to build Windows desktop applications.`
My distro is Devuan 4 (fork of Debian 11) on x64.
