### ISSUE TITLE
Is there any hope to complete the decompilation of all code

### ISSUE THREAD

**Issue by zajanmy** [djkaty/Il2CppInspector#47]
Hi
Is there any hope to complete the decompilation of all code

**Comment by djkaty** [comment]
That will never happen with a very high degree of accuracy. Your best bet is to use the decompilation tools built into products like IDA and Ghidra to look at the generated pseudo-C code. Tools like Il2CppInspector make the code much more readable by allowing you to generate Python scripts that add type and symbol annotations to everything in the binary.

Start learning assembly language (it's actually not that hard!) 🙂

**Comment by zajanmy** [comment]
> 这将永远不会以很高的准确性发生。最好的选择是使用IDA和Ghidra等产品中内置的反编译工具查看生成的伪C代码。Il2CppInspector之类的工具使您可以生成Python脚本，从而向二进制文件中的所有内容添加类型和符号注释，从而使代码更具可读性。
> 
> 开始学习汇编语言（实际上并不难！） 🙂



> Hi
> Is there any hope to complete the decompilation of all code



> That will never happen with a very high degree of accuracy. Your best bet is to use the decompilation tools built into products like IDA and Ghidra to look at the generated pseudo-C code. Tools like Il2CppInspector make the code much more readable by allowing you to generate Python scripts that add type and symbol annotations to everything in the binary.
> 
> Start learning assembly language (it's actually not that hard!) 🙂

Thank you for your reply. Can I see the API calling process of Unity in ida?

**Comment by djkaty** [comment]
Yes, IDA is a disassembler so you can load in an IL2CPP binary and look through all of the assembler code. This will let you see all of the calls made. You can see some quick examples of this in my blog here: https://katyscode.wordpress.com/2020/06/24/il2cpp-part-1/

**Comment by zajanmy** [comment]
> 拨打的电话。您可以

thank you
