### ISSUE TITLE
Issue with path format

### ISSUE THREAD

**Issue by Skrimel** [djkaty/Il2CppInspector#52]
When path contains name of folder with the russian letters and with whitespaces the target file cannot be found in console application

**Comment by djkaty** [comment]
Copying some random Russian characters from Google:

![image](https://user-images.githubusercontent.com/4500319/87259765-ef378180-c4ad-11ea-8d47-fcea755e1a42.png)

I wasn't able to reproduce this problem:

![image](https://user-images.githubusercontent.com/4500319/87259751-d9c25780-c4ad-11ea-8c76-7e4127671f56.png)

(I don't have the Russian font set but copied the file path into the command prompt)

You must surround the path in quotes or apostrophes if you are using a path with whitespace. Could you confirm whether it works when you do this?

**Comment by Skrimel** [comment]
Yes, surrounding the path in quotes solved the issue.
