### ISSUE TITLE
APK file only ARM64 detected 

### ISSUE THREAD

**Issue by AndnixSH** [djkaty/Il2CppInspector#54]
I have 2 Android games that contains multiple architectures but if you drop an APK file, it only detected ARM64 in the image list

![image](https://user-images.githubusercontent.com/40742924/88908000-9e6bab00-d259-11ea-89e1-2db28dba60c8.png)

This game contains 3 archs, ARMv7 ARM64 and x86 https://apkcombo.com/en-dk/south-park-phone-destroyer%E2%84%A2-battle-card-game/com.ubisoft.dragonfire/

This game contains 2 archs, ARMv7 and ARM64 https://apkcombo.com/%E3%83%95%E3%82%A1%E3%83%B3%E3%82%BF%E3%82%B7%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B32-es-%E6%9C%AC%E6%A0%BC%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3rpg/com.sega.PhantasyStarOnline2es/

**Comment by djkaty** [comment]
Thanks for the bug report Andnix, I'll look into it when I have some time 🙂

**Comment by djkaty** [comment]
This issue is resolved in commit https://github.com/djkaty/Il2CppInspector/commit/9ee316e8b2183c56e671a9405c093d7940d3513d !

**Comment by AndnixSH** [comment]
Thanks for the commit, it works now :)

**Comment by djkaty** [comment]
Awesome!

I just posted a new tutorial, this is an in-depth guide on extracting
protobufs:

https://katyscode.wordpress.com/2020/08/10/practical-il2cpp-protobuf/

It's the first of a series of tutorials, hope you enjoy it. It's for Fall
Guys which is a brand new and popular MMO-ish battle royale-ish game on
Steam, so if there's anywhere good to post it (I don't really follow the
game hacking forums as you know) to drive some traffic, feel free to do
that :)

Katy.
