### ISSUE TITLE
ERROR: Metadata file supplied is not a supported version[24]

### ISSUE THREAD

**Issue by Anonymoser** [djkaty/Il2CppInspector#6]
Unhandled Exception: System.Exception: ERROR: Metadata file supplied is not a supported version[24].
   at Il2CppInspector.Metadata..ctor(Stream stream)
   at Il2CppInspector.Il2CppProcessor.LoadFromFile(String codeFile, String metadataFile)
   at Il2CppInspector.App.Main(String[] args)

Why?

"Supports metadata versions 21, 22, 23 and 24"???

**Comment by Anonymoser** [comment]
Please anyone

GameAssembly.dll : http://www.mediafire.com/file/a6b0lmgdda839ix/GameAssembly.dll/file
global-metadata.dat : http://www.mediafire.com/file/r0go8ss6yr8zsbv/global-metadata.dat/file

**Comment by djkaty** [comment]
If you're still alive, please could you upload these files again? I have pushed a ton of changes over the last days and would like some more test material :) (and yes, I know I'm 18 months late... sorry)

**Comment by StijnSimons** [comment]
Different assembly, same error.
[content.zip](https://github.com/djkaty/Il2CppInspector/files/3758830/content.zip)

**Comment by djkaty** [comment]
That's an ELF64 binary which is not currently supported, however I'm working on the 64-bit file formats now and needed a sample so I'll use this to implement the necessary code, many thanks!

**Comment by StijnSimons** [comment]
> That's an ELF64 binary which is not currently supported, however I'm working on the 64-bit file formats now and needed a sample so I'll use this to implement the necessary code, many thanks!
> 
> Edit: it's also ARM64 ISA which also isn't supported but I'm writing the code for that right now :)

Thank you so much! (This is the Pokemon Go lib2cpp by the way)

**Comment by djkaty** [comment]
The ARM64 code is working and committed, but it won't help you yet. Been working on the ELF64 stuff all day, will continue tomorrow :)

**Comment by djkaty** [comment]
ELF64 support is added in commit https://github.com/djkaty/Il2CppInspector/commit/baf11e517a56d8d30a727214f737a1ad50839c9c

@StijnSimons The software is not capable of finding the needed metadata automatically yet. You can get the output you want by fudging in the following code at line 68 of Il2CppBinary.cs:

`Configure(subImage, 0x39FCA40, 0x39FCAB0); return true;`

Please let me know if that produces the correct results for you. I will begin working on auto-detection code for this kind of ARM compilation.

Thanks!

**Comment by StijnSimons** [comment]
> ELF64 support is added in commit [baf11e5](https://github.com/djkaty/Il2CppInspector/commit/baf11e517a56d8d30a727214f737a1ad50839c9c)
> 
> @StijnSimons The software is not capable of finding the needed metadata automatically yet. You can get the output you want by fudging in the following code at line 68 of Il2CppBinary.cs:
> 
> `Configure(subImage, 0x39FCA40, 0x39FCAB0); return true;`
> 
> Please let me know if that produces the correct results for you. I will begin working on auto-detection code for this kind of ARM compilation.
> 
> Thanks!

It successfully automatically detected the metadata and exported it.
Might contribute to generate a Python script to import the extracted data into IDA.

Thank you

**Comment by djkaty** [comment]
Working as of commit https://github.com/djkaty/Il2CppInspector/commit/2236764715ed8fcc4d0a076b3199c70cb0223f59 :)

**Comment by djkaty** [comment]
> Might contribute to generate a Python script to import the extracted data into IDA.

That is actually on my list of things to do, but I'm still learning my way around IDA's Python API so any contribution would be great :)

**Comment by StijnSimons** [comment]
> > Might contribute to generate a Python script to import the extracted data into IDA.
> 
> That is actually on my list of things to do, but I'm still learning my way around IDA's Python API so any contribution would be great :)

Use `import idaapi` to first import the IDA API, then you can use
- `idc.set_cmt` -> set comment
- `idc.set_name` -> set name
- `idc.get_func_attr` -> get func attribute
- `ida_funcs.del_func` -> delete func
- `ida_funcs.add_func(start, end)` -> (re)add func
...

For more information, check https://github.com/idapython/src.
