### ISSUE TITLE
!

### ISSUE THREAD

**Issue by ianpei** [djkaty/Il2CppInspector#60]
!

**Comment by ianpei** [comment]
And I make make great efforts！
I arrival at a conclusion 
The il2cpp-functions.h & il2cpp-types.h
cant passed the ndk compiler  enviroment!
wating a reply thank you!

**Comment by ianpei** [comment]
Im working for it still...
& can you split the .h files then make a include with summary file
my pc 32G memery shut down always in Android studio or idea

**Comment by djkaty** [comment]
Android support for C++ projects is on the development roadmap for the future but does not currently have a target date, so in the meantime you have to fudge it.

The Windows.h header is only needed to get the base address of the image with GetModuleBaseAddressW(). For Android, take all of the files in `appdata` and use the `init_il2cpp()` function in `framework/il2cpp-init.cpp` to process all of the headers. Re-implement `GetBaseAddress()` to return the base address of the image and you're good to go. In the future, Il2CppInspector will hopefully output a project suitable for Android as an option so you won't have to do this.

As to the rest of what you said, the code is standard C and the NDK should have no problem using it. The headers are already split by category and included via `il2cpp-init.cpp`. We may consider splitting up `il2cpp-types.h` in the future but need to implement dependency handling first. There should be no problem developing with 32GB RAM unless something else is wrong with the installation or hardware.

Finally, please do not spam the issue tracker or edit titles and posts to get attention. This project is developed in my spare time for free. When I have time to reply, I will reply. Posting repeatedly creates a nuisance in my inbox and does not lead me to reply faster or be more helpful. Thank you.

**Comment by ianpei** [comment]
Sorry! For spam the issue,when im thinking Im doing a rubsh issue!
