### ISSUE TITLE
Unsupported executable file format for UnityFramework

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#67]
Hi Kat,
   Thanks for great work. I had an issue that when I tried to analyze the binary file UnityFramework which has version 2019.3.0f6, it said Unsupported executable file format both Mac/Windows version. However it can be done by using Il2CppDumper. Can you take a look? Thanks!

The zip file contains both binary and metadata.
https://www.dropbox.com/s/4cyhvz1fmeeh5aa/UnityFramework.zip?dl=0

**Comment by djkaty** [comment]
Hey there! This bug is now fixed for MacOS in the latest commit but you didn't send over the Windows version so that may require an additional fix. Can you test and send the file if necessary?

**Comment by cctgapp** [comment]
> Hey there! This bug is now fixed for MacOS in the latest commit but you didn't send over the Windows version so that may require an additional fix. Can you test and send the file if necessary?
Hi Kat,
Thanks for your effort. For Windows version, maybe you misunderstood, what I meant was Il2CppInspector windows version, not the file.
BTW, after I re-download and rebuild again, It can go on but stuck at some point. See below:
>Il2CppInspector  -i UnityFramework
Il2CppInspector Command-Line Edition
Version 2020.2
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.2
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Unknown symbol type: 2c   0000000005614542   radr://5614542
Symbol table(s) found with 2310 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000000117B54
CodeRegistration struct found at 0x0000000004181D80 (file offset 0x04181D80)
MetadataRegistration struct found at 0x00000000042676A8 (file offset 0x042676A8)
IL2CPP binary version 24.2
Analyze IL2CPP data: 4.43 sec
Processing image 0 - ARM64 / 64-bit
Create .NET type model: 2.48 sec
Unknown symbol type: 2c   0000000005614542   radr://5614542
IL2CPP API discovery was successful
Selected Unity version(s) 2019.3.0 - 2019.3.6 (types: 2019.3.0 - 2019.3.6, APIs: 2019.3.0 - 2019.3.15)
Create C++ application model: 10.57 sec       <<- hang in here.

**Comment by djkaty** [comment]
```
IL2CPP API discovery was successful
Selected Unity version(s) 2019.3.0 - 2019.3.6 (types: 2019.3.0 - 2019.3.6, APIs: 2019.3.0 - 2019.3.15)
Create C++ application model: 15.95 sec
Generate C# code: 41.66 sec
Generate C++ code: 6.66 sec
Generate JSON metadata: 4.92 sec
Generate IDA Python script: 0.00 sec
```

You probably just need to wait longer :)

**Comment by cctgapp** [comment]
> You probably just need to wait longer :)

Hi Kat,
You're correct.

**Comment by djkaty** [comment]
It's also way more accurate.

I did actually spend a while in the profiler yesterday when I saw how long the C# output took, since I did also note that the runtime was abnormally long compared to most of my test cases. There are a couple of bottlenecks but it's mostly specific to this particular binary due to the large amount of scanning for custom attributes required.

If you want it to output faster I recommend you use the layout flag, eg. `-l x` where x is namespace, assembly, class or tree (`class` and `tree` will produce the fastest results). This will parallelize the output - something Il2CppDumper doesn't currently implement - and use all of the cores on your CPU to generate the C#. This is not parallelized when outputting a single file.

You can also use the Windows GUI which will only generate internal models of the data you actually want to output. The CLI assumes you want everything and generates everything, leading to a longer runtime.

**Comment by cctgapp** [comment]
> It's also way more accurate.
> 
> I did actually spend a while in the profiler yesterday when I saw how long the C# output took, since I did also note that the runtime was abnormally long compared to most of my test cases. There are a couple of bottlenecks but it's mostly specific to this particular binary due to the large amount of scanning for custom attributes required.
> 
> If you want it to output faster I recommend you use the layout flag, eg. `-l x` where x is namespace, assembly, class or tree (`class` and `tree` will produce the fastest results). This will parallelize the output - something Il2CppDumper doesn't currently implement - and use all of the cores on your CPU to generate the C#. This is not parallelized when outputting a single file.
> 
> You can also use the Windows GUI which will only generate internal models of the data you actually want to output. The CLI assumes you want everything and generates everything, leading to a longer runtime.
Good Job. Thank you so much.

**Comment by djkaty** [comment]
You're welcome :)

**Comment by djkaty** [comment]
Hey again,

I've implemented some speedups to the C# code generation that will hopefully make it run a little bit faster for you. The final commit of the changes is https://github.com/djkaty/Il2CppInspector/commit/835636d99e0897a9401f9398e4b5a5bd94fd27b8 . Let me know if that helps!

**Comment by cctgapp** [comment]
@djkaty It do speed up when in parallel processing.
