### ISSUE TITLE
Many of this type of unity framework of generics of methods cant call success !

### ISSUE THREAD

**Issue by ianpei** [djkaty/Il2CppInspector#71]
`DO_APP_FUNC(0x007BAF20, Font *, Resources_GetBuiltinResource_2, (String * path, MethodInfo * method));`
This is a unity framework method!

Call this method crash with a singal  ‘fault addr 00000018’！

The corresponding c# code is

```
public static T GetBuiltinResource<T>(string path)
			where T : UnityEngine.Object;

```

Many of this type of methods cant call success !

Under current conditions，other common methods is work well ！

Mabe other feature 'static'!

**Comment by djkaty** [comment]
You'll need to supply a valid MethodInfo for that to work.

Were you ever able to solve your other problem?

**Comment by ianpei** [comment]
No,I give up call new by type

**Comment by ianpei** [comment]
but how can i get methodinfo ?

**Comment by djkaty** [comment]
There are different ways to get MethodInfo. For vtable calls each VirtualInvokeData entry in the vtable contains a method pointer and a MethodInfo*. Otherwise, you can call the API il2cpp_class_get_method_from_name etc.

Re: your original problem, try to clone the latest build of Il2CppInspector. The "TypeInfo" pointers are now double-indirected, ie. Foo__TypeInfo**, so they will not be locked to whatever value they were when init_il2cpp() is first called. This is a breaking change of course so make sure you replace any TypeInfo with *TypeInfo in your existing code.

If there are types missing from il2cpp-types.h which should be there, I will need to see the metadata and binary files to reproduce the issue and solve it.

**Comment by ianpei** [comment]
[LessTypeResources.zip](https://github.com/djkaty/Il2CppInspector/files/5218350/LessTypeResources.zip)
 il2cpp-types.h cnat find 'Resources'
& can you give me a simple code 
I want to call 'il2cpp_class_get_method_from_name' , but I dont kown how to get param 'Il2CppClass * klass'

then I want got Il2CppClass by 'il2cpp_class_from_name' but i  dont kwon how to get the param 'const Il2CppImage * image'

This method i want call didnt called by game itself i cant hook it

**Comment by ianpei** [comment]
& I found many of il2cpp-function-api functions  is unuseful , called return 0x0, did you get any infomation?
such as il2cpp_class_from_name、il2cpp_domain_get_assemblies   etc. 

```
size_t assemb_count;
Il2CppDomain* doamin = il2cpp_domain_get();
LOGE("il2cpp-api-functions doamin is %p",doamin);
const Il2CppAssembly** allAssemb = il2cpp_domain_get_assemblies(doamin, &assemb_count);
LOGE("il2cpp-api-functions allAssemb: %p assemb_count is %d",allAssemb,assemb_count);
```

```
2020-09-15 02:32:35.006 11889-11889/com.DefaultCompany.NewUnityProject1 E/xNative: il2cpp-api-functions doamin is 0xe0ba0fe0
2020-09-15 02:32:35.006 11889-11889/com.DefaultCompany.NewUnityProject1 E/xNative: il2cpp-api-functions allAssemb: 0x0 assemb_count is 0
```

**Comment by ianpei** [comment]
before your reply, I think i get the solution , I called the method too early.
I strongly recommend you make the scaffoding by api based.
Here i found a project ! 
Augmentability  lower than yours ,but it is base il2cpp api.

https://github.com/brandonhenry/UnityHelper

part of Its submoudle 
https://github.com/sc2ad/beatsaber-hook/blob/af34a70c26049e222f46bc57d3721862a6ff74a1/shared/utils/il2cpp-utils.cpp

**Comment by djkaty** [comment]
`Il2CppClass *` object pointers are what you get when you use `*Foo__TypeInfo`, so if you want to get a `MethodInfo*` for Console.WriteLine with 1 argument you can do eg.:

 ```cpp
MethodInfo *method = il2cpp_class_get_method_from_name(*Console__TypeInfo, "WriteLine", 1);
```

(I haven't tested this but that's the principle).

Usage example for IL2CPP APIs here: https://github.com/djkaty/Il2CppInspector/issues/39#issuecomment-661808065

If that doesn't work for you, the APIs may have been tampered with by the application author.

I will look into why `UnityEngine.Resources` is not showing up in il2cpp-types.h

(I wrote all this before your latest message)

**Comment by djkaty** [comment]
The C++ scaffoldiing project feature is very new and was only released in the most recent version of Il2CppInspector. It is still undergoing a lot of changes and should be considered experimental. The priority for this first version was to make it work at all. Improvements such as the helper APIs you're asking for will come later on.

**Comment by ianpei** [comment]
I think  the greatest rays of light of you project is the scaffoldiing!
If it work well! 
Why i need ida for Binary modification ?
Why I need other  fearture?
I think want to be a common coder than a binary coder!
I think most humman want to be if he found it!

**Comment by lifeengines** [comment]
> I think the greatest rays of light of you project is the scaffoldiing!
> If it work well!
> Why i need ida for Binary modification ?
> Why I need other fearture?
> I want to be a common coder than a binary coder!
> I think most humman want to be if he found it!

other part are awsome too.and some tiny fix Binary patch is much more easier

**Comment by djkaty** [comment]
Did you solve your problem?

I still have it on my todo list to check why Resources is not showing up in il2cpp-types.h but I've been very busy this week and likely will be next week also.

**Comment by djkaty** [comment]
The issue with some missing classes in the C++ scaffolding output is fixed in the latest commit :)
