### ISSUE TITLE
Errors while using the IDA python script

### ISSUE THREAD

**Issue by Anthy1x** [djkaty/Il2CppInspector#74]
Hello, i have an issue similar to #57:
```
Generated script file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
Processing Types
Error .\il2cpp.h:1535: Type 'Object' is already defined
Error .\il2cpp.h:1567: Type 'String' is already defined
Error .\il2cpp.h:1571: Type 'Boolean' is already defined
Error .\il2cpp.h:1659: Type 'Byte' is already defined
Error .\il2cpp.h:1842: Type 'Object' is already defined
Error .\il2cpp.h:1843: Syntax error near: }
Error .\il2cpp.h:1856: Type 'Object' is already defined
Error .\il2cpp.h:1858: Syntax error near: }
Error .\il2cpp.h:1907: Type 'String' is already defined
Error .\il2cpp.h:1908: Type 'String' is already defined
Error .\il2cpp.h:1909: Type 'String' is already defined
Error .\il2cpp.h:1912: Syntax error near: }
Error .\il2cpp.h:1919: Type 'Object' is already defined
Error .\il2cpp.h:1928: Syntax error near: }
Error .\il2cpp.h:1935: Type 'Object' is already defined
Error .\il2cpp.h:1945: Syntax error near: }
Error .\il2cpp.h:1952: Type 'Object' is already defined
Error .\il2cpp.h:1962: Syntax error near: }
Error .\il2cpp.h:1978: Type 'String' is already defined
Error .\il2cpp.h:1979: Type 'String' is already defined
Processing method definitions
SetType(0xa80678, 'String * Locale_GetText_1(String * fmt, Object__Array * args, MethodInfo * method)') failed!
SetType(0xa95918, 'String * Runtime_GetNativeStackTrace(Exception * exception, MethodInfo * method)') failed!
SetType(0x55b4f4, 'void RuntimeClassHandle__ctor(RuntimeClassHandle__Boxed * this, RuntimeStructs_MonoClass * value, MethodInfo * method)') failed!
SetType(0x55b4fc, 'void RuntimeClassHandle__ctor_1(RuntimeClassHandle__Boxed * this, void * ptr, MethodInfo * method)') failed!
SetType(0x55b528, 'RuntimeStructs_MonoClass * RuntimeClassHandle_get_Value(RuntimeClassHandle__Boxed * this, MethodInfo * method)') failed!
SetType(0x55b530, 'bool RuntimeClassHandle_Equals(RuntimeClassHandle__Boxed * this, Object * obj, MethodInfo * method)') failed!
SetType(0x55b538, 'int32_t RuntimeClassHandle_GetHashCode(RuntimeClassHandle__Boxed * this, MethodInfo * method)') failed!
SetType(0xa95aa4, 'void * RuntimeClassHandle_GetTypeFromClass(RuntimeStructs_MonoClass * klass, MethodInfo * method)') failed!
SetType(0x55b56c, 'RuntimeTypeHandle RuntimeClassHandle_GetTypeHandle(RuntimeClassHandle__Boxed * this, MethodInfo * method)') failed!
...
```

I've gone through 'il2cpp.h' and didn't find any redefined types. Also, the python script i used which generated this error was output by a build of your latest commit. The same error happened with the current release of Il2CppInspector so that's why i decided to build the latest commit and give it another go.

**Comment by Anthy1x** [comment]
I'm attaching the global-metadata file and libil2cpp if it'd help you resolve the issue.

[global-metadata.txt(.dat)](https://github.com/djkaty/Il2CppInspector/files/5219809/global-metadata.txt)
[libil2cpp.txt(.so)](https://github.com/djkaty/Il2CppInspector/files/5219812/libil2cpp.txt)

**Comment by Anthy1x** [comment]
I noticed the errors go away if i just rename them(obviously). However, i'm not sure where these types have been defined already so the problem will most likely occur again..

**Comment by djkaty** [comment]
Hey Anthy1x,

Thanks for your bug report. Since you closed the issue, did you find a solution?

**Comment by Anthy1x** [comment]
I did but it's more of a hotfix and not an actual solution. I modified the line [CppNamespace.cs:68](https://github.com/djkaty/Il2CppInspector/blob/master/Il2CppInspector.Common/Cpp/CppNamespace.cs#L68) to append a suffix to the name. That seems to have resolved it for me.

**Comment by Anthy1x** [comment]
Since there are no type conflicts within 'il2cpp.h' then my best guess is that _maybe_ the names are conflicting with some internal IDA types......??

**Comment by djkaty** [comment]
Okay, that's really bizarre because we already handle a lot of IDA keywords (see https://github.com/djkaty/Il2CppInspector/blob/835636d99e0897a9401f9398e4b5a5bd94fd27b8/Il2CppInspector.Common/Cpp/CppDeclarationGenerator.cs#L548 ), and of course every app has Object, String, Boolean etc. and I haven't experienced these issues.

So, I will re-open this ticket and take a look at the files you sent and get back to you.

**Comment by djkaty** [comment]
I loaded the files you sent into IDA Pro 7.2 and ran the generated Python script and it executed with no errors.

Which version of IDA are you using?
Python 2 or 3?
Are you including any other type libraries / C headers/source?

The procedure I usually use is:
1. Load the binary with all of the default settings
2. Press Alt+F7 and run the script when the disassembly listing opens
3. Do anything else afterwards

**Comment by djkaty** [comment]
Closing issue as OP has not responded.
