### ISSUE TITLE
The supplied metadata file is not valid.

### ISSUE THREAD

**Issue by toxic-devoloper** [djkaty/Il2CppInspector#76]
Whats wrong?
(password: 1)
[password-1.zip](https://github.com/djkaty/Il2CppInspector/files/5224583/password-1.zip)

**Comment by lifeengines** [comment]
encrypted

**Comment by lifeengines** [comment]
the exe file use VMProtect protected.

**Comment by toxic-devoloper** [comment]
Very thanks)
