### ISSUE TITLE
Ghidra Script Broken

### ISSUE THREAD

**Issue by jakecrowley** [djkaty/Il2CppInspector#83]
I exported the 'il2cpp.py' file to my 'ghidra_scripts' directory, however when I tried to run the script it flooded my screen with "Invalid Function Signature" as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/8465805/94102655-a2065300-fe00-11ea-8dad-6c3259ec319e.png)

I have also uploaded the il2cpp.h and il2cpp.json files, in case the error is specific to my project: [il2cpp.zip](https://github.com/djkaty/Il2CppInspector/files/5273542/il2cpp.zip)

**Comment by djkaty** [comment]
I didn't look at your files but I suspect you probably didn't use the Parse C Source feature of Ghidra to import the types before running the script. I've added a check for this in the script in the latest commit. See https://github.com/djkaty/Il2CppInspector/blob/master/README.md#adding-metadata-to-your-ghidra-workflow for the full instructions 👍
