### ISSUE TITLE
How do I use the python IDA script?

### ISSUE THREAD

**Issue by blueboy90780** [djkaty/Il2CppInspector#87]
Hi I'm very new and tried searching this everywhere with no answers. Il2CppInspector can generate a python script but what do I need to do to run this script? I tried using the normal python IDE but some libraries can't be imported...

**Comment by djkaty** [comment]
For the IDA script you need IDA: https://www.hex-rays.com/products/ida/

For the Ghidra script you need Ghidra: https://ghidra-sre.org/

The scripts are for use with these disassemblers. If you have never used a disassembler, or are unfamiliar with assembly language, you should familiarize yourself with these before diving in at the deep end with il2cpp :)
