### ISSUE TITLE
Unsupported executable file format (Mach-O ARM64 / ARMv8-A)

### ISSUE THREAD

**Issue by zkitX** [djkaty/Il2CppInspector#89]
Here is a zip of the metadata and binary.
[UnityFramework.framework.zip](https://github.com/djkaty/Il2CppInspector/files/5330012/UnityFramework.framework.zip)

**Comment by djkaty** [comment]
This file works fine for me on the latest commit of Il2CppInspector. Please could you compile and check 👍

**Comment by zkitX** [comment]
Building from the latest commit works, thanks.
