### ISSUE TITLE
C++ Scafolding code example doesn't work anymore

### ISSUE THREAD

**Issue by matteoturini** [djkaty/Il2CppInspector#93]
```cpp
void Run()
{
    Vector3__Boxed* myVector3 = (Vector3__Boxed*)il2cpp_object_new((Il2CppClass*)*Vector3__TypeInfo);

    Vector3__ctor(myVector3, 1.0f, 2.0f, 3.0f, NULL);

    LogWrite(to_string(myVector3->fields.y));
}
```
no suitable conversion function from "app::Vector3__Class" to "Il2CppClass *" exists

**Comment by reolat** [comment]
Hello!
The example from the Readme.md is for the version 2020.2.1 beta. Newest release is 2020.2. If you want to use this example you need to clone & compile Il2CppInspector yourself.

**Comment by djkaty** [comment]
Hey, sorry for the slow reply, what @reolat wrote is indeed correct. To use the example in 2020.2, remove the `*` before `Vector3__TypeInfo` in the call to `il2cpp_object_new`. The TypeInfos were changed from single to double indirect pointers in 2020.2.1 beta.

I'll close this now, feel free to re-open if you have further problems.
