### ISSUE TITLE
Error while building IL2CppDLL project

### ISSUE THREAD

**Issue by shazgames** [djkaty/Il2CppInspector#94]
After downloading and compiling latest Il2CppInspector, I generated IL2CppDLL VS project and tried to compile it in release x86 but got error.
```
1>------ Build started: Project: IL2CppDLL, Configuration: Release Win32 ------
1>helpers.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)
1>C:\Users\Provious\Desktop\shit\gmmm\Release\IL2CppDLL.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "IL2CppDLL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by shazgames** [comment]
This error throws ```return std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t>{}.to_bytes(u16);``` function in helpers.cpp

**Comment by djkaty** [comment]
Which MSVC++ build tools version are you using? You may wish to try the Visual Studio 2017 tools (I believe it's 14.0 rather than 14.2, don't remember exactly).

**Comment by shazgames** [comment]
@djkaty I'm using vs 2017

**Comment by djkaty** [comment]
I was mistaken in my earlier post. Having checked it, I was able to reproduce the issue with the Visual Studio 2017 (v141) platform toolset. Using the Visual Studio 2019 (v142), compilation succeeded. So your choices are:

1. Install Visual Studio 2019 (the toolset will be added to VS2017 as well), or
2. Remove the two `il2cppi_to_string` functions from `helpers.cpp` if you don't need them, which should enable the compile to work

I'd be grateful if you could let me know if this solves the problem, as I should either update the README or add an #if around those functions if so.

**Comment by djkaty** [comment]
Commit https://github.com/djkaty/Il2CppInspector/commit/84f2e5e57907caa3bb811aec43656e7fad1e69e3 will allow you to compile the scaffolding projects with Visual Studio 2017, however you will lose access to `il2cppi_to_string`.

Hope that helps!
