### ISSUE TITLE
[question] What is vp_Value_1_System_Int32_ ?

### ISSUE THREAD

**Issue by keepitsmpl** [djkaty/Il2CppInspector#97]
First of all, nice job on the tool, it works like a charm.

This is not really a "issue" but rather a question... 

Inside the .h generated by the program i found:

`struct vp_Value_1_System_Int32_ * CurrentWeaponAmmoCount;`
this is a member from another structure. 

Im wondering - how could i read this in c++? It just returns a pointer, i tried reading the address that it gives me but no sucess.

What the game does is:
```
if ( !v3 || (v4 = v3->fields._.CurrentWeaponAmmoCount) == 0i64 || (v5 = (Func_1_Int32_ *)v4->fields.Get) == 0i64 )
    sub_1801C52B0(0i64);
  return Func_1_Int32__Invoke(v5, vp_Value_1_V_Getter_1_System_Int32_System_Int32__Invoke__MethodInfo);
```

I tried fields.get aswell but i also recived a pointer.. Any thoughts?

**Comment by keepitsmpl** [comment]
Nvm, looks like it is a custom int32 wrapper. There is a function that is responsable to "translate" it. 

auto ConvertToINT = ( int32_t( __stdcall * )( Func_1_Int32_ , MethodInfo * ) )( ( uintptr_t ) Globals::Var::GameAssembly + ( uintptr_t ) 0x00824DA0 ) ;
auto iii = ConvertToINT( *( Func_1_Int32_ * ) LocalPlayer.fields._.CurrentWeaponClipCount->fields.Get , NULL );

**Comment by djkaty** [comment]
Glad you got it figured out 🙂
