### ISSUE TITLE
ghidra python file error

### ISSUE THREAD

**Issue by josuamanuel13** [djkaty/Il2CppInspector#99]
i was try to run the python script on ghidra then i get thousand off errors for the game Dead Trigger i was testing with other games and still getting the same errors
![image](https://user-images.githubusercontent.com/60289470/97775474-33e63780-1af4-11eb-9ef6-aa1a56262a76.png)

**Comment by djkaty** [comment]
Did you follow the instructions in the README.md to import the C types first before running the script?

If you're still having trouble, try building from the latest commit.

Let me know how it goes.

**Comment by josuamanuel13** [comment]
ok thanks for the answer i will read the readme.md file and try again, if it works i will let you know!

**Comment by djkaty** [comment]
Closing. Feel free to re-open if you are still having issues!

**Comment by josuamanuel13** [comment]
ok
